"""
manuscript_audit_table.py -- the map from every load-bearing figure the
manuscript prints to the artifact key it must come from.

Imported by audit_manuscript_numbers.py, which does the reading and the
comparing. The table lives in its own file because it is the part a reviewer
argues with: one row per printed figure, in the order the manuscript prints
them, each naming the file and the key.

    (id, printed literal, artifact, dotted key, section, note)

`artifact=None` marks a figure with no artifact expected -- a closed form
checked under DERIVED, a value from the cited literature, or a run parameter.
Those are reported NO SOURCE unless the note says why, because "no artifact"
is the finding this audit exists to surface.

Rounding: a row is compared at the precision the manuscript prints. Where the
printed value and the artifact disagree only in the last digit because the
manuscript computed from a rounded input, the row stays and the MISMATCH is
reported -- the audit does not get to choose which of the two is right.
"""
from __future__ import annotations

import math

#: Rows retired by the third revision (2026-09-23), with the reason. Kept as
#: a record so a literal that comes back is noticed rather than silently
#: re-audited against a key nobody re-checked.
RETIRED = {
    "obs_duration": "107.106 s (II-A now prints the UTC start/stop only)",
    "f2_line": "the F2 frame pixel 1120.3 / 3676.9",
    "f2_sample": "the F2 frame pixel 1120.3 / 3676.9",
    "rms_resid": "the float32 rms residual (III-B prints the maximum only)",
    "putrevu_az": "Putrevu SLC spacing 0.55 m (C12: geometry compressed to one sentence)",
    "putrevu_rg": "Putrevu SLC spacing 9.6 m (C12)",
    "putrevu_rho_lo": "the 0.29-0.35 altitude range of the bound (C12)",
    "putrevu_rho_hi": "the 0.29-0.35 altitude range of the bound (C12)",
    "kc_sigma": "the 0.02-point sampling error of the shared-texture check (C13)",
    "t3_264_crit": "2.64 -- now printed to three decimals, keyed as sens_crit_264",
    "t3_530_crit": "1.96 -- now printed to three decimals, keyed as sens_crit_530",
    "t3_622_crit": "1.86 -- now printed to three decimals, keyed as sens_crit_622",
    "cr_0": "17.6, the rho = 0 Monte Carlo row -- V-C now prints the analytic F value 17.5",
}

AUDIT = [
    # =================================================================
    # II. THE PRODUCT, AND THE TWO MASKS
    # =================================================================
    ("looks21", "21", "docs/enl_predictions.json",
     "predictions[0].declared.azimuth_looks", "II", "label field"),
    ("look_bw", "51.016", "docs/enl_predictions.json",
     "predictions[0].declared.azimuth_look_bandwidth", "II", "label field"),
    ("bw_label", "1071.336", "docs/enl_predictions.json",
     "predictions[0].declared.total_processed_azimuth_bandwidth", "II", "label field"),
    ("prf", "3321.64", "docs/enl_predictions.json",
     "predictions[0].declared.pulse_repetition_frequency", "II", "label field"),
    ("kcal", "70.308868", "docs/enl.json",
     "label.calibration_constant", "II", "label field, sri product"),
    # III-A: the constant with its unit, and the per-channel gains
    ("kcal_db_ortho", "70.308868", "docs/dop_exclusion.json", "calibration.K_db", "III",
     "unit dB, ortho (sri) label; K = 10^(K_dB/10) is calibration.K_lin. The SLC "
     "label's 80.0 dB is a different product's constant"),
    ("gain_g_lh", "1.018", "docs/dop_exclusion.json", "gain_imbalance.LH", "III",
     "label gain imbalance, LH"),
    ("gain_g_lv", "1.001", "docs/dop_exclusion.json", "gain_imbalance.LV", "III",
     "label gain imbalance, LV"),
    ("geo_nodes", "937,296", "data/pradan/dfsar/metadata_real.json",
     "geodetic_frame.isro_geolocation_grid_agreement.nodes_compared", "II", None),
    ("geo_rms_sample", "0.2846", "data/pradan/dfsar/metadata_real.json",
     "geodetic_frame.isro_geolocation_grid_agreement.sample_residual_px.rms", "II", None),
    ("geo_rms_line", "0.4550", "data/pradan/dfsar/metadata_real.json",
     "geodetic_frame.isro_geolocation_grid_agreement.line_residual_px.rms", "II", None),
    ("psr_jaccard", "0.714", "docs/psr_validation.json",
     "jaccard", "II", "against the LOLA team's published PSR mask"),
    ("frame_px", "14,943,444", "docs/landing_sites.json",
     "search.pixels_evaluated", "II", "2258 x 6618, the full frame"),
    ("frame_km2", "9339.65", "frontend/public/analysis/faustini.json",
     "grid.frame_area_km2", "II", None),
    ("foot_px", "5,324,545", "frontend/public/analysis/faustini.json",
     "masks.footprint.pixels", "II", "ISRO sri_ma > 0"),
    ("foot_km2", "3327.84", "frontend/public/analysis/faustini.json",
     "masks.footprint.area_km2", "II", None),
    ("foot_frac", "35.63", "frontend/public/analysis/faustini.json",
     "masks.footprint.fraction", "II", "fraction stored; printed as a percentage"),
    ("valid_px", "2,337,086", "frontend/public/analysis/faustini.json",
     "masks.amplitude.pixels", "II", "(LH > 0) & (LV > 0)"),
    ("amp_km2", "1460.68", "frontend/public/analysis/faustini.json",
     "masks.amplitude.area_km2", "II", None),
    ("cov_amp", "15.64", "frontend/public/analysis/faustini.json",
     "masks.amplitude.fraction", "II", "fraction stored; printed as a percentage"),
    ("amp_over_pointed", "43.89", "frontend/public/analysis/faustini.json",
     "masks.returned_over_pointed", "II", "fraction stored; printed as a percentage"),
    ("f2_disc", "1521", "docs/f2_footprint.json",
     "disc_pixels", "II", "44 px diameter at 25 m"),
    ("cov_f2", "17.09", "docs/f2_footprint.json",
     "disc_amplitude_fraction", "II", "fraction stored; printed as a percentage"),
    ("f2_cpr", "1.95", "docs/detection_statistics.json",
     "published_reanalysis.rows[0].cpr", "II", "Sinha et al. 2026, transcribed"),

    # =================================================================
    # III. THE AMPLITUDE-ONLY DEGENERACY
    # =================================================================
    ("slc_q5", "0.89", "docs/stokes_from_slc.json",
     "results.t3a.slc_21look_boxcar5_sqrt_ratio[0]", "III",
     "5th percentile, SLC 21-look + boxcar5 sqrt(l_H/l_V)"),
    ("slc_q95", "1.18", "docs/stokes_from_slc.json",
     "results.t3a.slc_21look_boxcar5_sqrt_ratio[4]", "III", "95th percentile"),
    ("del_q5", "0.93", "docs/stokes_from_slc.json",
     "results.t3a.delivered_boxcar5_sqrt_DN2_ratio[0]", "III",
     "5th percentile, sqrt(boxcar5(DN^2)) ratio at matched ENL"),
    ("del_q95", "1.17", "docs/stokes_from_slc.json",
     "results.t3a.delivered_boxcar5_sqrt_DN2_ratio[4]", "III", "95th percentile"),
    ("x_bound", "0.2614797", None, None, "III",
     "2*artanh(0.13); closed form, checked as DERIVED below"),
    ("ceiling", "4.261e-3", "docs/degeneracy_replication.json",
     "closed_form_ceiling", "III", "tanh^2(artanh(0.13)/2)"),
    ("ceiling_full", "4.2610829e-3", "docs/degeneracy_replication.json",
     "closed_form_ceiling", "III", "the same constant to eight figures"),
    ("factor", "235", "frontend/public/analysis/sweep_grid.json",
     "crossing.factor_below_published", "III", "1.00 / measured crossing"),
    ("dop_excluded", "40.21", "docs/dop_exclusion.json",
     "excluded_percent", "III", "DOP_a >= 0.13, excluded whatever the phase"),
    ("dop_undecidable", "59.79", "docs/dop_exclusion.json",
     "undecidable_percent", "III", "the remainder; undecidable from amplitudes"),
    ("valid_px_fig", "2,337,086", "docs/dop_exclusion.json",
     "measured_pixels", "III", "the same count, recomputed in Fig. 1's own path"),
    ("max_resid_stored", "1.241e-6", "frontend/public/analysis/faustini.json",
     "cpr_dop_identity.max_abs_residual", "III", "stored float32 field"),
    ("crossing", "4.2610574e-3", "frontend/public/analysis/sweep_grid.json",
     "crossing.cpr_value", "III", "max CPR where DOP < 0.13, screened field"),
    ("crossing_rel", "5.99e-6", None, None, "III",
     "relative agreement, crossing vs closed form; DERIVED"),
    ("gen_crossing", "8.6e-5", "docs/degeneracy_replication.json",
     "products[1].relative_agreement", "III",
     "the 2020-03-05 acquisition's crossing, relative to the closed form"),
    # ---- the Monte Carlo of the proxy ---------------------------------
    ("mc_N", "5", "docs/cpr_significance.json",
     "monte_carlo[0].n_looks", "III", "look count the simulator ran at"),
    ("mc_trials", "120 000", "docs/cpr_significance.json",
     "monte_carlo_run.trials_per_row", "III",
     "the run parameter, now recorded: the committed artifact reproduces "
     "bit-for-bit at --trials 120000 --coherence 0.9822"),
    ("rho", "0.9822", "docs/cpr_significance.json",
     "monte_carlo_run.coherence", "III",
     "the coherence the run used; equal to sqrt(0.9647), checked as DERIVED"),
    ("lhlv_corr", "0.9647", "docs/cpr_significance.json",
     "native_proxy.lh_lv_local_correlation", "III", None),
    ("mc_stokes_med_03", "0.300", "docs/cpr_significance.json",
     "monte_carlo[0].stokes_cpr.median", "III", None),
    ("mc_stokes_med_07", "0.700", "docs/cpr_significance.json",
     "monte_carlo[1].stokes_cpr.median", "III", None),
    ("mc_stokes_med_10", "1.000", "docs/cpr_significance.json",
     "monte_carlo[2].stokes_cpr.median", "III", None),
    ("mc_stokes_med_15", "1.500", "docs/cpr_significance.json",
     "monte_carlo[3].stokes_cpr.median", "III", None),
    ("mc_proxy_med_07", "0.00043", "docs/cpr_significance.json",
     "monte_carlo[1].amplitude_proxy.median", "III", None),
    ("mc_proxy_1db", "0.00331", "docs/cpr_significance.json",
     "monte_carlo[4].amplitude_proxy.median", "III", "1 dB imbalance"),
    ("mc_proxy_3db", "0.02922", "docs/cpr_significance.json",
     "monte_carlo[5].amplitude_proxy.median", "III", "3 dB imbalance"),
    # ---- III-D, the propagation bound ---------------------------------
    ("cpr_with_sin", "0.053411", "docs/incidence_audit.json",
     "screening_blast_radius.cpr_max_with_sin", "III", None),
    ("cpr_without_sin", "0.053852", "docs/incidence_audit.json",
     "screening_blast_radius.cpr_max_without", "III", None),
    ("dcpr_max", "1.310e-2", "docs/propagation_percentiles.json",
     "cpr.over_amplitude_mask.max", "III", None),
    ("ddop_max", "1.393e-1", "docs/propagation_percentiles.json",
     "dop.over_amplitude_mask.max", "III", None),
    ("dcpr_med", "2.3e-5", "docs/propagation_percentiles.json",
     "cpr.over_amplitude_mask.p50", "III", None),
    ("ddop_med", "1.1e-3", "docs/propagation_percentiles.json",
     "dop.over_amplitude_mask.p50", "III", None),
    # ---- III-E, the Stokes vector from the SLC ------------------------
    # III-E: the published aggregation and the per-pixel bound
    ("sinha_dop_lo", "0.10", "docs/literature_screen.json",
     "records[?id=4].aggregation_record.average_dop_range[0]", "III",
     "literature value; the quotation is recorded with it"),
    ("sinha_dop_hi", "0.13", "docs/literature_screen.json",
     "records[?id=4].aggregation_record.average_dop_range[1]", "III", None),
    ("band_hi_2dp", "1.30", "docs/stokes_from_slc.json",
     "results.invariant.t3f_coupling_band.band[1]", "III",
     "'every one with a measured CPR below 1.30'"),
    ("win_rank_corr", "0.98", "docs/stokes_from_slc.json",
     "results.t3e.180_deg.coherence_predicts_cpr.spearman", "III",
     "Spearman, (1-rho)/(1+rho) of each window's median H-V coherence against its "
     "median CPR, 20 windows"),
    ("dop_bias_n14", "7", "docs/dop_sampling_bias.json",
     "manuscript_figure.closed_form_percent", "III",
     "P(m_hat < 0.13 | DOP 0, N 14) = Beta(3/2, 13) cdf at 0.13^2; simulated 7.05 "
     "+/- 0.04 % in rows[1]"),
    ("band_lo", "0.7699", "docs/stokes_from_slc.json",
     "results.invariant.t3f_coupling_band.band[0]", "III", "(1-0.13)/(1+0.13)"),
    ("band_hi", "1.2989", "docs/stokes_from_slc.json",
     "results.invariant.t3f_coupling_band.band[1]", "III", "(1+0.13)/(1-0.13)"),
    ("slc_cells", "5,883,594", "docs/stokes_from_slc.json",
     "slc.matched_cells", "III", "21-look x 5x5 cells with both channels positive"),
    ("coh_med", "0.658", "docs/stokes_from_slc.json",
     "results.invariant.coherence.median", "III", None),
    ("coh_q1", "0.464", "docs/stokes_from_slc.json",
     "results.invariant.coherence.iqr[0]", "III", None),
    ("coh_q3", "0.786", "docs/stokes_from_slc.json",
     "results.invariant.coherence.iqr[1]", "III", None),
    ("coh_win_med", "0.174", "docs/stokes_from_slc.json",
     "results.invariant.coherence.per_window_summary.median", "III",
     "over the 20 most homogeneous 15x15 windows"),
    ("coh_win_min", "0.09", "docs/stokes_from_slc.json",
     "results.invariant.coherence.per_window_summary.min", "III", None),
    ("coh_win_max", "0.64", "docs/stokes_from_slc.json",
     "results.invariant.coherence.per_window_summary.max", "III", None),
    ("dop_frac", "1.50", "docs/stokes_from_slc.json",
     "results.invariant.dop_below_threshold.fraction", "III",
     "fraction stored; printed as a percentage"),
    ("dop_win_med", "11", "docs/stokes_from_slc.json",
     "results.invariant.dop_below_threshold.per_window_summary.median", "III",
     "fraction stored; printed as a percentage"),
    ("dop_win_max", "32", "docs/stokes_from_slc.json",
     "results.invariant.dop_below_threshold.per_window_summary.max", "III",
     "fraction stored; printed as a percentage"),
    ("phase_mean", "-88.3", "docs/stokes_from_slc.json",
     "results.sign.phase_evidence.circular_mean_deg", "III", None),
    ("phase_R", "0.946", "docs/stokes_from_slc.json",
     "results.sign.phase_evidence.resultant_length", "III", None),
    ("quadrature", "1.7", "docs/stokes_from_slc.json",
     "results.sign.phase_evidence.residual_from_quadrature_deg", "III", None),
    ("s3_effect", "0.04", "docs/stokes_from_slc.json",
     "results.sign.phase_evidence.effect_on_S3_percent", "III",
     "100(1 - cos 1.67 deg)"),
    ("med_180", "0.21", "docs/stokes_from_slc.json",
     "results.sign.admissible_readings.180_deg", "III", "the physical sign"),
    ("med_0", "4.73", "docs/stokes_from_slc.json",
     "results.sign.admissible_readings.0_deg", "III", "its reciprocal"),
    ("joint_cond", "29.9", "docs/stokes_from_slc.json",
     "results.joint_measured.conditional.fraction", "III",
     "P(CPR>1 | DOP<0.13); fraction stored, printed as a percentage"),
    ("joint_all", "0.45", "docs/stokes_from_slc.json",
     "results.joint_measured.unconditional.fraction", "III",
     "fraction stored; printed as a percentage"),

    # =================================================================
    # IV. THE EQUIVALENT NUMBER OF LOOKS
    # =================================================================
    ("enl16_lh", "5.30", "docs/enl.json",
     "patch_sizes.16.LH.on_DN_squared.mode", "IV", "16x16 patches, delivered"),
    ("enl16_lv", "6.46", "docs/enl.json",
     "patch_sizes.16.LV.on_DN_squared.mode", "IV", None),
    ("enl_lh", "5.83", "docs/enl.json", "boxcar_gain.LH.enl_raw", "IV",
     "over the screening mask"),
    ("enl_lv", "5.14", "docs/enl.json", "boxcar_gain.LV.enl_raw", "IV", None),
    ("patches", "8,337", "docs/bootstrap_enl.json", "LH.n_patches", "IV", None),
    ("boot_lh_lo", "4.03", "docs/bootstrap_enl.json",
     "LH.enl_raw_ci_block[0]", "IV", "block bootstrap, B = 2000"),
    ("boot_lh_hi", "6.19", "docs/bootstrap_enl.json",
     "LH.enl_raw_ci_block[1]", "IV", None),
    ("boot_lv_lo", "4.38", "docs/bootstrap_enl.json",
     "LV.enl_raw_ci_block[0]", "IV", None),
    ("boot_lv_hi", "7.29", "docs/bootstrap_enl.json",
     "LV.enl_raw_ci_block[1]", "IV", None),
    ("boot_lh5_lo", "10.7", "docs/bootstrap_enl.json",
     "LH.enl_box_ci_block[0]", "IV", "after the 5x5 boxcar"),
    ("boot_lh5_hi", "22.5", "docs/bootstrap_enl.json",
     "LH.enl_box_ci_block[1]", "IV", None),
    ("boot_lv5_lo", "12.1", "docs/bootstrap_enl.json",
     "LV.enl_box_ci_block[0]", "IV", None),
    ("boot_lv5_hi", "24.8", "docs/bootstrap_enl.json",
     "LV.enl_box_ci_block[1]", "IV", None),
    ("cov_lo", "12", "docs/enl_benchmark.json",
     "synthetic.speckle_only_summary.coverage_percent_range[0]", "IV",
     "coverage of the nominally 95 % block bootstrap, synthetic speckle"),
    ("cov_hi", "26", "docs/enl_benchmark.json",
     "synthetic.speckle_only_summary.coverage_percent_range[1]", "IV", None),
    ("mode_bias", "16", "docs/enl_benchmark.json",
     "synthetic.speckle_only_summary.relative_bias_percent_median", "IV",
     "the mode estimator's relative bias on correlated speckle"),
    ("bias_n4", "0.68", "docs/enl_benchmark.json",
     "synthetic.speckle_only_summary.bias_at_lowest_N.bias", "IV", "at N = 4"),
    ("bias_n12", "1.86", "docs/enl_benchmark.json",
     "synthetic.speckle_only_summary.bias_at_highest_N.bias", "IV", "at N = 12"),
    ("corrected_raw", "5.0", "docs/enl_benchmark.json",
     "synthetic.speckle_only_summary.raw_enl_5p83_corrected", "IV",
     "5.83 read through the measured bias"),
    ("enl32_lh", "2.64", "docs/enl.json",
     "patch_sizes.32.LH.on_DN_squared.mode", "IV", None),
    ("pb_field_az", "0.84", "docs/patch_bias.json", "rho_az", "IV",
     "FIELD correlation used in the patch-bias run"),
    ("pb_field_rg", "0.58", "docs/patch_bias.json", "rho_rg", "IV", None),
    ("pb_lag_az", "0.71", "docs/patch_bias.json",
     "field_intensity_lag1.azimuth", "IV", "the INTENSITY lag-one it produces"),
    ("pb_lag_rg", "0.34", "docs/patch_bias.json",
     "field_intensity_lag1.range", "IV", None),
    ("pb_16", "6.61", "docs/patch_bias.json", "correlated.16.mode", "IV", None),
    ("pb_32", "6.01", "docs/patch_bias.json", "correlated.32.mode", "IV", None),
    ("pb_unc", "6.00", "docs/patch_bias.json",
     "uncorrelated_control.16", "IV", "uncorrelated control at both sizes"),
    ("stat_lo", "3.3", "docs/stationarity.json", "enl_min", "IV",
     "over the four blocks with coverage"),
    ("stat_hi", "8.0", "docs/stationarity.json", "enl_max", "IV", None),
    # ---- IV-B, the control --------------------------------------------
    ("bw_measured", "1071.2", "docs/slc_multilook_control.json",
     "medians.measured_bandwidth_hz", "IV", "median across the nine windows"),
    ("bw_min", "1071.2", "docs/slc_multilook_control.json",
     "windows[*].measured_bandwidth_hz|min", "IV", "'1071.2--1071.6 Hz across the nine windows'"),
    ("bw_max", "1071.6", "docs/slc_multilook_control.json",
     "windows[*].measured_bandwidth_hz|max", "IV", None),
    ("sl_median", "1.04", "docs/slc_multilook_control.json",
     "medians.enl_single_look", "IV", "single-look intensity, answer known"),
    ("sl_min", "0.93", "docs/slc_multilook_control.json",
     "min.enl_single_look", "IV", None),
    ("sl_max", "1.12", "docs/slc_multilook_control.json",
     "max.enl_single_look", "IV", None),
    ("osamp", "3.10", "docs/slc_multilook_control.json",
     "medians.oversampling_factor", "IV", None),
    ("two_wt", "6.77", "docs/slepian_ceiling.json",
     "two_WT_asymptotic", "IV", "21 / 3.10, asymptotic"),
    ("part_ratio", "7.34", "docs/slepian_ceiling.json",
     "participation_ratio_rectangular", "IV", "exact, rectangular spectrum"),
    ("shaped", "7.38", "docs/slepian_ceiling.json",
     "enl_mildly_shaped_spectrum", "IV", "1 - 0.1 cos(2 pi f / B)"),
    ("hamming", "4.07", "docs/slepian_ceiling.json",
     "enl_hamming_054", "IV", "the shape the label declares"),
    ("spatial", "4.52", "docs/slc_multilook_control.json",
     "medians.enl_spatial_21", "IV", None),
    ("subband", "9.95", "docs/slc_multilook_control.json",
     "medians.enl_subband_21", "IV", None),
    ("width_sp", "0.95", "docs/mechanism_controls.json",
     "medians.width_az_spatial", "IV", "azimuth ACF half-width, output rows"),
    ("width_sb", "2.79", "docs/mechanism_controls.json",
     "medians.width_az_subband", "IV", None),
    ("paired", "4.47", "docs/mechanism_controls.json",
     "paired_difference_subband_minus_spatial.mean", "IV", "nine windows, paired"),
    ("paired_se", "0.43", "docs/mechanism_controls.json",
     "paired_difference_subband_minus_spatial.se", "IV", None),
    ("matched", "-1.00", "docs/mechanism_controls.json",
     "paired_difference_at_matched_width.mean", "IV",
     "sub-band minus spatial once the finer arm is smoothed to the coarser width"),
    ("matched_se", "0.57", "docs/mechanism_controls.json",
     "paired_difference_at_matched_width.se", "IV", None),
    ("trace_moment", "6.09", "docs/enl_benchmark.json",
     "slc_spatial_arm.estimators.trace_moment_2x2.mode", "IV", None),
    ("log_cumulant", "4.83", "docs/enl_benchmark.json",
     "slc_spatial_arm.estimators.log_cumulant_2x2.mode", "IV", None),
    ("moment_lh", "4.64", "docs/enl_benchmark.json",
     "slc_spatial_arm.estimators.moment_LH.mode", "IV", None),
    # ---- IV-C, the generality test ------------------------------------
    ("gen_looks", "39", "docs/enl_predictions.json",
     "predictions[2].declared.azimuth_looks", "IV", "2020-03-05 L-band"),
    ("gen_osamp", "2.905", "docs/enl_predictions.json",
     "predictions[2].oversampling", "IV", None),
    ("gen_reference", "13.42", "docs/enl_predictions.json",
     "predictions[2].predicted_ceiling", "IV", "registered before the product was opened"),
    ("gen_part_ratio", "14.04", "docs/slepian_ceiling.json",
     "other_products[1].participation_ratio_rectangular", "IV",
     "39 samples at oversampling 2.905"),
    ("gen_lh", "2.28", "docs/enl_generality.json",
     "measurements[4].measured_enl", "IV", None),
    ("gen_lv", "2.21", "docs/enl_generality.json",
     "measurements[5].measured_enl", "IV", None),
    ("gen_attained", "0.17", "docs/enl_generality.json",
     "measurements[4].attained_fraction", "IV", None),
    ("here_attained", "0.86", "docs/enl_generality.json",
     "measurements[0].attained_fraction", "IV", "this pass, for comparison"),
    # ---- IV-D, spatial averaging --------------------------------------
    ("lag_az", "0.838", "docs/enl.json",
     "lag_correlation.LH.azimuth_lines[0]", "IV", None),
    ("lag_rg", "0.576", "docs/enl.json",
     "lag_correlation.LH.range_samples[0]", "IV", None),
    ("eroded_px", "2,294,084", "docs/enl_estimator_spec.json",
     "masks.enl_measurement_mask.n_px", "IV", "amplitude mask eroded by 5x5"),
    ("gain_lh", "2.35", "docs/enl.json", "boxcar_gain.LH.gain", "IV", None),
    ("gain_lv", "3.84", "docs/enl.json", "boxcar_gain.LV.gain", "IV",
     "the manuscript says \"on the unrounded estimates\": 3.8449 -> 3.84"),
    ("enl5_lh", "13.72", "docs/detection_statistics.json",
     "effective_looks.screened_field.lh", "IV", None),
    ("enl5_lv", "19.77", "docs/detection_statistics.json",
     "effective_looks.screened_field.lv", "IV", None),

    # =================================================================
    # V. DETECTION STATISTICS
    # =================================================================
    ("n_sc", "12.7", "docs/stokes_from_slc.json",
     "results.t3d_180.enl_sc.enl", "V", "same-sense circular ENL, physical sign"),
    ("n_oc", "18.1", "docs/stokes_from_slc.json",
     "results.t3d_180.enl_oc.enl", "V", "opposite-sense"),
    ("floor38", "1.44", None, None, "V",
     "sqrt((2N-1)/(N-2)) at N = 38, ratio of relSD(R) to 1/sqrt(N); DERIVED"),
    ("floor6", "1.66", None, None, "V", "the same at N = 6; DERIVED"),
    # Table II, seven rows by five columns, at the N each row prints
    ("t2_n5_sd", "0.775", "docs/detection_statistics.json",
     "sampling_statistics.rows[0].rel_sd", "V", None),
    ("t2_n5_bias", "1.250", "docs/detection_statistics.json",
     "sampling_statistics.rows[0].bias", "V", None),
    ("t2_n5_crit", "2.978", "docs/detection_statistics.json",
     "sampling_statistics.rows[0].crit_95", "V", None),
    ("t2_n5_p07", "29.16", "docs/detection_statistics.json",
     "sampling_statistics.rows[0].p_exceed_true_cpr_0p7_percent", "V", None),
    ("t2_n5_p05", "14.48", "docs/detection_statistics.json",
     "sampling_statistics.rows[0].p_exceed_true_cpr_0p5_percent", "V", None),
    ("t2_n677_sd", "0.623", "docs/detection_statistics.json",
     "sampling_statistics.rows[1].rel_sd", "V", None),
    ("t2_n677_bias", "1.173", "docs/detection_statistics.json",
     "sampling_statistics.rows[1].bias", "V", None),
    ("t2_n677_crit", "2.525", "docs/detection_statistics.json",
     "sampling_statistics.rows[1].crit_95", "V", None),
    ("t2_n677_p07", "26.03", "docs/detection_statistics.json",
     "sampling_statistics.rows[1].p_exceed_true_cpr_0p7_percent", "V", None),
    ("t2_n677_p05", "10.75", "docs/detection_statistics.json",
     "sampling_statistics.rows[1].p_exceed_true_cpr_0p5_percent", "V", None),
    ("t2_n875_sd", "0.529", "docs/detection_statistics.json",
     "sampling_statistics.rows[2].rel_sd", "V", None),
    ("t2_n875_bias", "1.129", "docs/detection_statistics.json",
     "sampling_statistics.rows[2].bias", "V", None),
    ("t2_n875_crit", "2.244", "docs/detection_statistics.json",
     "sampling_statistics.rows[2].crit_95", "V",
     "at the N the row prints (8.75); at_measured_N gives 2.243 from the "
     "unrounded median 8.7544, and both are in the artifact"),
    ("t2_n875_p07", "23.16", "docs/detection_statistics.json",
     "sampling_statistics.rows[2].p_exceed_true_cpr_0p7_percent", "V", None),
    ("t2_n875_p05", "7.85", "docs/detection_statistics.json",
     "sampling_statistics.rows[2].p_exceed_true_cpr_0p5_percent", "V",
     "at the N the row prints; at_measured_N gives 7.84"),
    ("t2_n1372_sd", "0.405", "docs/detection_statistics.json",
     "sampling_statistics.rows[3].rel_sd", "V",
     "at the N the row prints (13.72); at_measured_N gives 0.406 from the "
     "unrounded ENL 13.7166"),
    ("n_edge", "80", "docs/detection_statistics.json",
     "derived.n_at_which_crit_equals_band_edge.N", "V",
     "'the critical value falls to 1.2989 only at N ~ 80'; 79.62"),
    ("t2_n1372_bias", "1.079", "docs/detection_statistics.json",
     "sampling_statistics.rows[3].bias", "V", None),
    ("t2_n1372_crit", "1.895", "docs/detection_statistics.json",
     "sampling_statistics.rows[3].crit_95", "V", None),
    ("t2_n1372_p07", "17.79", "docs/detection_statistics.json",
     "sampling_statistics.rows[3].p_exceed_true_cpr_0p7_percent", "V", None),
    ("t2_n1372_p05", "3.74", "docs/detection_statistics.json",
     "sampling_statistics.rows[3].p_exceed_true_cpr_0p5_percent", "V", None),
    ("t2_n1977_sd", "0.331", "docs/detection_statistics.json",
     "sampling_statistics.rows[4].rel_sd", "V", None),
    ("t2_n1977_bias", "1.053", "docs/detection_statistics.json",
     "sampling_statistics.rows[4].bias", "V", None),
    ("t2_n1977_crit", "1.698", "docs/detection_statistics.json",
     "sampling_statistics.rows[4].crit_95", "V", None),
    ("t2_n1977_p07", "13.32", "docs/detection_statistics.json",
     "sampling_statistics.rows[4].p_exceed_true_cpr_0p7_percent", "V", None),
    ("t2_n1977_p05", "1.60", "docs/detection_statistics.json",
     "sampling_statistics.rows[4].p_exceed_true_cpr_0p5_percent", "V", None),
    ("t2_n21_sd", "0.321", "docs/detection_statistics.json",
     "sampling_statistics.rows[5].rel_sd", "V", None),
    ("t2_n21_bias", "1.050", "docs/detection_statistics.json",
     "sampling_statistics.rows[5].bias", "V", None),
    ("t2_n21_crit", "1.671", "docs/detection_statistics.json",
     "sampling_statistics.rows[5].crit_95", "V", None),
    ("t2_n21_p07", "12.59", "docs/detection_statistics.json",
     "sampling_statistics.rows[5].p_exceed_true_cpr_0p7_percent", "V", None),
    ("t2_n21_p05", "1.35", "docs/detection_statistics.json",
     "sampling_statistics.rows[5].p_exceed_true_cpr_0p5_percent", "V", None),
    ("t2_n38_sd", "0.234", "docs/detection_statistics.json",
     "sampling_statistics.rows[6].rel_sd", "V", None),
    ("t2_n38_bias", "1.027", "docs/detection_statistics.json",
     "sampling_statistics.rows[6].bias", "V", None),
    ("t2_n38_crit", "1.462", "docs/detection_statistics.json",
     "sampling_statistics.rows[6].crit_95", "V", None),
    ("t2_n38_p07", "6.11", "docs/detection_statistics.json",
     "sampling_statistics.rows[6].p_exceed_true_cpr_0p7_percent", "V", None),
    ("t2_n38_p05", "0.14", "docs/detection_statistics.json",
     "sampling_statistics.rows[6].p_exceed_true_cpr_0p5_percent", "V", None),
    # Table III, the sensitivity rows
    ("t3_264_n", "6.21", "docs/table5_sensitivity.json", "rows[0].N", "V", None),
    ("t3_264_p07", "26.9", "docs/table5_sensitivity.json",
     "rows[0].fp_percent_at_cpr_0p7", "V", None),
    ("t3_530_n", "12.47", "docs/table5_sensitivity.json", "rows[1].N", "V", None),
    ("t3_530_p07", "19.0", "docs/table5_sensitivity.json",
     "rows[1].fp_percent_at_cpr_0p7", "V", None),
    ("t3_583_p07", "17.8", "docs/table5_sensitivity.json",
     "rows[2].fp_percent_at_cpr_0p7", "V", None),
    ("t3_622_raw", "6.22", "docs/table5_sensitivity.json",
     "rows[3].raw_enl", "V", "amplitude-domain ENL"),
    ("t3_622_n", "14.64", "docs/table5_sensitivity.json", "rows[3].N", "V", None),
    ("t3_622_p07", "17.0", "docs/table5_sensitivity.json",
     "rows[3].fp_percent_at_cpr_0p7", "V", None),
    ("crit_lo", "1.64", "docs/bootstrap_enl.json",
     "LH.floor_ci_block[0]", "V", "block-bootstrap range of the critical value"),
    ("crit_hi", "2.07", "docs/bootstrap_enl.json",
     "LH.floor_ci_block[1]", "V", None),
    ("exceed_lo", "11.8", "docs/bootstrap_enl.json",
     "LH.fp_ci_block[0]", "V", None),
    ("exceed_hi", "20.8", "docs/bootstrap_enl.json",
     "LH.fp_ci_block[1]", "V", None),
    # power
    ("power_1299", "16.4", "docs/detection_statistics.json",
     "sampling_statistics.power_at_operating_point.rows[1].power_percent", "V",
     "at the largest true CPR the DOP condition admits"),
    ("power_15", "27", "docs/detection_statistics.json",
     "sampling_statistics.power_at_operating_point.rows[2].power_percent", "V", None),
    ("power_20", "56", "docs/detection_statistics.json",
     "sampling_statistics.power_at_operating_point.rows[3].power_percent", "V", None),
    ("power_30", "88", "docs/detection_statistics.json",
     "sampling_statistics.power_at_operating_point.rows[4].power_percent", "V", None),
    # background range
    ("sens_crit_264", "2.638", "docs/detection_statistics.json",
     "derived.sensitivity_crit_three_decimals.rows[0].crit_95_at_printed_N", "V",
     "at N = 6.21; 2.6376 at the unrounded 6.2128 rounds alike"),
    ("sens_crit_530", "1.957", "docs/detection_statistics.json",
     "derived.sensitivity_crit_three_decimals.rows[1].crit_95_at_printed_N", "V",
     "at N = 12.47"),
    ("sens_crit_622", "1.855", "docs/detection_statistics.json",
     "derived.sensitivity_crit_three_decimals.rows[3].crit_95_at_printed_N", "V",
     "at N = 14.64"),
    ("bg_04", "1.0", "docs/detection_statistics.json",
     "derived.p_exceed_at_operating_point.rows[0].p_exceed_percent", "V",
     "P(R > 1) at N = 13.72, true CPR 0.4"),
    ("bg_112", "62", "docs/detection_statistics.json",
     "derived.p_exceed_at_operating_point.rows[6].p_exceed_percent", "V",
     "true CPR 1.12"),
    ("bg_05", "3.7", "docs/background_cpr_sweep.json", "rows[2].fp_percent", "V", None),
    ("bg_08", "28", "docs/background_cpr_sweep.json", "rows[5].fp_percent", "V", None),
    ("bg_09", "39", "docs/background_cpr_sweep.json", "rows[6].fp_percent", "V", None),
    # V-B, the crater maximum
    ("corr_area", "61.42", "docs/cpr_significance.json",
     "effective_samples.area_all_lags", "V", "px per independent sample"),
    ("f2_eff", "25", "docs/cpr_significance.json",
     "effective_samples.f2_effective_samples", "V", "1521 px / 61.42"),
    ("f2_peak_eff", "2.52", "docs/cpr_significance.json",
     "f2_peak_cpr.5.effective", "V", "median peak, 25 effective samples, N = 5"),
    ("f2_peak_raw", "7.38", "docs/cpr_significance.json",
     "f2_peak_cpr.5.raw", "V", "the same over 1521 raw pixels"),
    ("f2_amp_px", "260", "docs/f2_maximum.json",
     "disc.amplitude_pixels", "V", "of the 1521-pixel disc"),
    ("f2_max_med", "1.91", "docs/f2_maximum.json",
     "results.N13p72.correlated_max_over_amplitude_pixels.median", "V", None),
    ("f2_max_p95", "2.73", "docs/f2_maximum.json",
     "results.N13p72.correlated_max_over_amplitude_pixels.p95", "V", None),
    ("f2_count", "46.5", "docs/f2_maximum.json",
     "results.N13p72.exceedance_count_over_amplitude_pixels.mean", "V", None),
    ("f2_count_se", "0.2", "docs/f2_maximum.json",
     "results.N13p72.exceedance_count_over_amplitude_pixels.se", "V", None),
    # V-C, in what sense the rates are upper bounds
    ("putrevu_cpr", "1.07", "docs/cpr_dispersion.json",
     "external_check.cpr_mean", "V", "Byrgius C, transcribed from print"),
    ("putrevu_relsd", "0.159", "docs/cpr_dispersion.json",
     "external_check.cpr_rel_sd", "V", None),
    ("putrevu_n", "54.88", "docs/cpr_dispersion.json",
     "external_check.led_with_triple.N", "V", None),
    ("putrevu_floor", "0.194", "docs/cpr_dispersion.json",
     "external_check.led_with_triple.independent_floor", "V", None),
    ("putrevu_rho", "0.31", "docs/cpr_dispersion.json",
     "external_check.led_with_triple.rho_I_min", "V", None),
    ("putrevu_alt_n", "81", "docs/cpr_dispersion.json",
     "external_check.N_from_dispersion_independent_channels", "V",
     "the same dispersion with no correlation at all"),
    ("f_n14_07", "17.5", "docs/detection_statistics.json",
     "derived.f_exceedance_N14_cpr0p7_percent", "V",
     "the analytic F(28, 28) value at CPR 0.7, 17.545; the rho = 0 Monte Carlo row "
     "of correlated_ratio.json reads 17.58 and is no longer printed"),
    ("cr_05", "14.1", "docs/correlated_ratio.json", "rows[1].fp_percent", "V", None),
    ("cr_08", "6.3", "docs/correlated_ratio.json", "rows[2].fp_percent", "V", None),
    ("cr_09", "1.9", "docs/correlated_ratio.json", "rows[3].fp_percent", "V", None),
    ("circ_corr", "0.50", "docs/stokes_from_slc.json",
     "results.t3d_180.corr_sc_oc", "V",
     "circular-channel INTENSITY correlation |corr(SC, OC)| over the frame -- not "
     "the field coherence gamma_c (third review M7; gamma_c is in "
     "stokes_from_slc.json::coherence_by_gate)"),
    ("blocks", "109", "docs/stokes_from_slc.json",
     "results.t3e.blocks_64x64.n_selected", "V", "64x64 blocks below the 10th CV pct"),
    ("tail_p95", "0.86", "docs/stokes_from_slc.json",
     "results.t3e.180_deg.blocks_64x64_summary.ratio_p95_median", "V",
     "empirical / F, within blocks"),
    ("tail_p99", "0.81", "docs/stokes_from_slc.json",
     "results.t3e.180_deg.blocks_64x64_summary.ratio_p99_median", "V", None),
    ("wc_nu8", "18.8", "docs/kclutter_within_cell.json",
     "rows[1].exceed_percent", "V", "within-cell texture, order 8"),
    ("win_corr", "0.14", "docs/stokes_from_slc.json",
     "results.t3e.180_deg.windows_15x15_summary.corr_median", "V",
     "circular-channel INTENSITY correlation in the 20 windows"),
    ("win_r95", "1.02", "docs/stokes_from_slc.json",
     "results.t3e.180_deg.windows_15x15_summary.ratio_p95_median", "V", None),
    ("win_r99", "0.98", "docs/stokes_from_slc.json",
     "results.t3e.180_deg.windows_15x15_summary.ratio_p99_median", "V", None),
    ("m_min_07", "0.176", "docs/joint_criterion.json", "m_min_at_true_cpr", "V",
     "|0.7 - 1|/(0.7 + 1)"),
    ("f2_eff", "24.8", "docs/detection_statistics.json",
     "derived.effective_samples_f2_disc.effective_samples", "V", "1521 / 61.42"),
    ("wc_nu4", "19.7", "docs/kclutter_within_cell.json",
     "rows[4].exceed_percent", "V", "order 4"),
    ("wc_base", "17.5", "docs/kclutter_within_cell.json",
     "rows[0].exceed_percent", "V",
     "no texture at N = 14, the same draw the textured rows use; the 17.8 of "
     "Table II is N = 13.72 and is a different row"),
    ("wc_enl8", "11.2", "docs/kclutter_within_cell.json",
     "rows[1].enl_of_textured_intensity", "V", None),
    ("wc_enl4", "9.3", "docs/kclutter_within_cell.json",
     "rows[4].enl_of_textured_intensity", "V",
     "order 4, INDEPENDENT per look -- the row whose exceedance is the 19.7 "
     "quoted beside it. rows[6] (lag-one 0.8) gives 5.05 and belongs to a "
     "different correlation setting"),
    ("joint_sim", "1.8", "docs/joint_criterion.json",
     "headline.joint_fp_percent", "V", "simulated on the Stokes vector, N = 14"),
    ("joint_marginal", "17.5", "docs/joint_criterion.json",
     "marginal_fp_percent_analytic_F", "V", None),

    # =================================================================
    # VI. MODEL-CONSISTENCY CHECK ON PUBLISHED DATA
    # =================================================================
    ("g2_hermite", "6.12", "docs/published_moments.json",
     "craters[0].excess_kurtosis", "VI", "transcribed from Fa & Cai Table 1"),
    ("g2_rozh", "7.66", "docs/published_moments.json",
     "craters[1].excess_kurtosis", "VI", None),
    ("g2_main", "7.06", "docs/published_moments.json",
     "craters[2].excess_kurtosis", "VI", None),
    ("g2_schom", "6.51", "docs/published_moments.json",
     "craters[3].excess_kurtosis", "VI", None),
    ("g2_card", "7.19", "docs/published_moments.json",
     "craters[4].excess_kurtosis", "VI", None),
    ("g2_byrg", "7.33", "docs/published_moments.json",
     "craters[5].excess_kurtosis", "VI", None),
    ("g2_doll", "7.00", "docs/published_moments.json",
     "craters[6].excess_kurtosis", "VI", None),
    ("g2_stev", "7.95", "docs/published_moments.json",
     "craters[7].excess_kurtosis", "VI", None),
    ("n_hermite_sd", "9.11", "docs/published_moments.json",
     "craters[0].N_from_dispersion", "VI", None),
    ("n_hermite_g1", "9.65", "docs/published_moments.json",
     "craters[0].N_from_skewness", "VI", None),
    ("n_hermite_g2", "9.94", "docs/published_moments.json",
     "craters[0].N_from_kurtosis", "VI", None),
    ("n_card_g1", "7.49", "docs/published_moments.json",
     "craters[4].N_from_skewness", "VI", "the widest per-crater spread"),
    ("n_card_g2", "9.12", "docs/published_moments.json",
     "craters[4].N_from_kurtosis", "VI", None),
    ("pm_med_sigma", "8.75", "docs/published_moments.json",
     "median_N_from_dispersion", "VI", None),
    ("pm_med_skew", "9.08", "docs/published_moments.json",
     "median_N_from_skewness", "VI", None),
    ("pm_med_kurt", "9.17", "docs/published_moments.json",
     "median_N_from_kurtosis", "VI", None),
    ("pm_spread", "3.8", "docs/published_moments.json",
     "agreement_sd_vs_skew_percent_from_printed_medians", "VI",
     "from the printed medians; from the unrounded ones it is 3.7"),
    # pm_exceed was here. Section VI no longer prints "at N = 8.75 the model
    # gives an exceedance of 23.16 %"; the only remaining occurrence of the
    # literal is Table II's 8.75 row, audited as t2_n875_p07 against
    # detection_statistics. published_moments.json still computes the same
    # figure under consequence_at_median_dispersion_N, unprinted.
    ("minirf_zoom_looks", "8", "docs/published_moments.json",
     "mode_table.zoom.nominal_looks", "VI", "presence check only; small integer"),
    ("minirf_zoom_cdr", "14.8", "docs/published_moments.json",
     "mode_table.zoom.cdr_pixel_spacing_m", "VI", "the product Fa & Cai analysed"),
    ("minirf_base_looks", "16", "docs/published_moments.json",
     "mode_table.baseline.nominal_looks", "VI", "presence check only; small integer"),
    ("minirf_base_res", "150", "docs/published_moments.json",
     "mode_table.baseline.resolution_m", "VI", None),
    ("minirf_effective", "6.7", "docs/published_moments.json",
     "mode_table.effective_looks_reported.value", "VI",
     "Spudis et al. 2013, attributed to unpublished analysis"),

    # =================================================================
    # VII-VIII. THE ZERO, THE SCOPE, THE SEARCH
    # =================================================================
    ("swath_max", "5.341e-2", "docs/detection_statistics.json",
     "per_pixel_significance.swath_max", "VIII", "peak CPR_a in the swath"),
    ("factor_full", "234.68", "frontend/public/analysis/sweep_grid.json",
     "crossing.factor_below_published", "VIII", None),
    ("scope_40", "40", "docs/dop_exclusion.json",
     "excluded_percent", "VIII", "rounded in the scope table"),
    ("lit_unique", "34", "docs/literature_search.json",
     "counts.unique", "VIII", "presence check only; small integer"),
    ("lit_excluded", "9", "docs/literature_search.json",
     "counts.excluded", "VIII", "presence check only; small integer"),
    ("lit_relevant", "25", "docs/literature_search.json",
     "counts.relevant", "VIII", "presence check only; small integer"),
    ("lit_fulltext", "14", "docs/literature_screen.json",
     "counts.access.full_text", "VIII", "after the 2026-09-16 re-screen"),
    ("lit_abstract", "11", "docs/literature_screen.json",
     "counts.access.abstract_only", "VIII", None),
    ("lit_links", "75", "docs/literature_screen.json",
     "original_search.raw_links_returned", "VIII", "from the search-flow record"),
]

#: Arithmetic checked here, with the inputs audited on their own rows.
DERIVED = [
    ("x_bound", 0.2614797, lambda: 2 * math.atanh(0.13), 1e-6),
    ("factor", 235.0, lambda: 1.0 / 0.004261057358235121, 1.0),
    ("t2_n1372_bias", 1.079, lambda: 13.72 / (13.72 - 1.0), 1e-3),
    ("floor38", 1.44, lambda: ((2 * 38 - 1) / (38 - 2)) ** 0.5, 5e-3),
    ("floor6", 1.66, lambda: ((2 * 6 - 1) / (6 - 2)) ** 0.5, 5e-3),
    ("crossing_rel", 5.99e-6,
     lambda: abs(0.004261057358235121 - 0.004261082862785302)
             / 0.004261082862785302, 5e-8),
    # "one cell in 66" was deleted from III-E as redundant with the 1.50 %;
    # the reciprocal is still in the artifact
    # (stokes_from_slc.json::...dop_below_threshold.one_cell_in = 66.54).
    # "a calibration field alone can move a pixel's DOP by 1.07x the width of
    # the 0.13 criterion"
    ("dop_ratio", 1.07, lambda: 0.1392841339111328 / 0.13, 5e-3),
    # the tail is narrower than F by 14 % and 19 % at those percentiles.
    # 19, not 20: 100 * (1 - 0.80520) = 19.48. The manuscript now states the
    # two percentiles separately instead of rounding them into a range.
    ("tail_gap_lo", 14.0, lambda: 100 * (1 - 0.859035173822312), 0.5),
    ("tail_gap_hi", 19.0, lambda: 100 * (1 - 0.8052039479277788), 0.5),
    # the ratio bias at the two look counts
    ("bias_n5_pct", 25.0, lambda: 100 * (5 / 4 - 1), 0.05),
    ("bias_n1372_pct", 7.9, lambda: 100 * (13.72 / 12.72 - 1), 0.05),
    # 21 x 51.016 reproduces the declared total processed bandwidth
    ("look_bw_product", 1071.336, lambda: 21 * 51.016, 5e-3),
    # the simulated coherence is the square root of the measured intensity
    # correlation under the circular-Gaussian relation
    ("rho_from_corr", 0.9822, lambda: 0.9647125999763775 ** 0.5, 5e-4),
    # III-E: a pixel at the F2 peak of 1.95 has DOP >= |1-1.95|/(1+1.95)
    ("f2_dop_min", 0.32, lambda: (1.95 - 1) / (1.95 + 1), 5e-3),
    # III-E: 0.658 gives 0.21, (1 - 0.658)/(1 + 0.658)
    ("coh_to_cpr", 0.21, lambda: (1 - 0.658042) / (1 + 0.658042), 5e-3),
    # V-B: 1521 / 61.42
    ("f2_eff_arith", 24.8, lambda: 1521 / 61.42, 0.05),
    # V-C: the analytic F(28, 28) exceedance at a true CPR of 0.7
    ("f28_07", 17.5, lambda: 17.544925186078576, 0.05),
]

#: "about X": compared at a stated RELATIVE tolerance, because the manuscript
#: says it is approximate. (id, printed, artifact, key, rel_tol, section, note)
APPROX = [
    ("win_pred_cpr", "0.7", "docs/stokes_from_slc.json",
     "results.t3e.180_deg.coherence_predicts_cpr.predicted_median", 0.05, "III",
     "'(about 0.7, more depolarized terrain)'; predicted 0.704"),
    ("win_obs_cpr", "0.7", "docs/stokes_from_slc.json",
     "results.t3e.180_deg.coherence_predicts_cpr.observed_median", 0.05, "III",
     "observed 0.718"),
    ("win_n_lo", "100", "docs/stokes_from_slc.json",
     "results.t3e.180_deg.windows_15x15_summary.n_sc_median", 0.05, "V",
     "'about 100 to 120': median N_SC 97.0"),
    ("win_n_hi", "120", "docs/stokes_from_slc.json",
     "results.t3e.180_deg.windows_15x15_summary.n_oc_median", 0.05, "V",
     "median N_OC 122.1"),
]

#: Identifiers printed verbatim. The artifact string must START WITH the
#: printed one (the manuscript drops the label's _xx_d18.xml suffix).
#: (id, printed, artifact, key, section, note)
STRINGS = [
    ("gen_product", "ch2_sar_ncxl_20200305t114902885_d_sri_xx_cp",
     "docs/enl_L_20200305.json", "label.source", "IV", "second acquisition"),
    ("main_product", "ch2_sar_ncxl_20200808t201154198_d_sri_xx_cp",
     "docs/dop_exclusion.json", "calibration.product", "II",
     "contained in the artifact's product field"),
]

#: QUANTIFIED CLAIMS -- "all", "every", "each", "identical", "in every one of".
#: The audit once passed "1071.2 Hz in all nine windows" and "3.10, identical
#: in all nine windows" because it compared the printed number with a MEDIAN
#: key: a claim about every element was checked against one summary of them.
#: Each row here tests the claim against EVERY element of the array behind it.
#:
#: (id, anchor, checks, section, note)
#:   anchor  -- regex that must match within 120 characters of the quantifier
#:              in the manuscript; it ties the row to the sentence. A LaTeX
#:              backslash is written \\ (in a raw string): \ref would be read
#:              as a carriage return and \, as a bare comma
#:   checks  -- list of (artifact, key-with-[*]-or-filter, test)
#:   test    -- ("rounds_to", "3.10")      every element rounds to it
#:              ("within", lo, hi)         every element in [lo, hi]
#:              ("below", x) / ("above", x) every element strictly below/above
#:              ("equals", v)              every element == v
#:              ("count", n)               the array has n elements
#:              ("all_are", "no")          every element is that string
#:              ("none_are", "yes")        no element is that string
#:              ("yes_only_for_id", 2)     "yes" appears, and only on record 2
QUANTIFIED = [
    ("q_proxy_every_case", r"0\.00043 in every case",
     [("docs/cpr_significance.json", "monte_carlo[0:4].amplitude_proxy.median",
       ("rounds_to", "0.00043"))],
     "III", "the four equal-power rows, CPR 0.30 / 0.70 / 1.00 / 1.50"),
    ("q_eq1_every_cell", r"interval\}\) at every cell",
     [("docs/stokes_from_slc.json", "results.t3b_180.violation_fraction", ("equals", 0.0)),
      ("docs/stokes_from_slc.json", "results.t3b_0.violation_fraction", ("equals", 0.0))],
     "III", "fraction of cells outside Eq. (1)'s band, both signs"),
    ("q_band_every_cell", r"at every cell with",
     [("docs/stokes_from_slc.json", "results.invariant.t3f_coupling_band.fraction_outside",
       ("equals", 0.0))],
     "III", "every DOP < 0.13 cell inside the coupling band"),
    ("q_selected_below_130", r"every one with a measured CPR below 1\.30",
     [("docs/stokes_from_slc.json", "results.invariant.t3f_coupling_band.fraction_outside",
       ("equals", 0.0)),
      ("docs/stokes_from_slc.json", "results.invariant.t3f_coupling_band.band[1]",
       ("below", 1.30))],
     "III", "no low-DOP cell outside (0.7699, 1.2989), and 1.2989 < 1.30"),
    ("q_bias_every_N", r"at every look count tes",
     [("docs/enl_benchmark.json", "synthetic.rows[?texture_label=inf].relative_bias",
       ("within", 0.14, 0.18))],
     "IV", "'about 16 % high at every look count tested': speckle-only rows, "
           "N = 4, 6, 8, 12, each within 14-18 %"),
    ("q_oversampling_nine", r"in every one of the nine windows",
     [("docs/slc_multilook_control.json", "windows[*].oversampling_factor",
       ("rounds_to", "3.10")),
      ("docs/slc_multilook_control.json", "windows[*].oversampling_factor", ("count", 9))],
     "IV", "the claim the median key once passed; now per window"),
    ("q_all_pixels_fig1", r"over all \$2\\,337\\,086\$",
     [("docs/dop_exclusion.json", "measured_pixels", ("equals", 2337086.0)),
      ("docs/dop_exclusion.json", "figure_cache_cross_check.n", ("equals", 2337086.0))],
     "III", "Fig. 1 is drawn over every measured pixel"),
    ("q_all_pixels_resid", r"across all\s+\$2\\,337\\,086\$",
     [("frontend/public/analysis/faustini.json", "cpr_dop_identity.verified_over_pixels",
       ("equals", 2337086.0))],
     "III", "the residual is taken over every measured pixel"),
    ("q_half_all_cells", r"half of all cells",
     [("docs/detection_statistics.json",
       "derived.p_exceed_at_operating_point.rows[?true_cpr=1.0].p_exceed_percent",
       ("within", 49.5, 50.5))],
     "V", "at a true CPR of 1.00, P(R > 1) = 0.5 exactly under F(2N, 2N)"),
    ("q_half_realizations", r"about half of all\s+realizations",
     [("docs/f2_maximum.json", "results.N13p72.correlated_max_over_amplitude_pixels.p_exceeds_crit",
       ("within", 0.40, 0.60))],
     "V", "P(max over the 260 pixels > 1.895), correlated-F rows"),
    ("q_table_every_N", r"critical value at every look count in",
     [("docs/detection_statistics.json", "sampling_statistics.rows[*].crit_95",
       ("above", 1.299))],
     "VIII", "every Table II critical value exceeds the band edge"),
    ("q_bias_every_study", r"uncorrected in\s+every lunar CPR study we examined",
     [("docs/literature_screen.json",
       "records[?relevant_lunar_cpr_ice_study=true].ratio_bias_corrected",
       ("all_are", "no"))],
     "VIII", "the screening record's per-study field for the N/(N-1) correction"),
    ("q_criterion_every_study", r"the criterion of\s+every study in",
     [], "V", "no per-record field records each study's criterion; UNBACKED"),
    # "none reports X" is a universal claim about the 25 screened records. It
    # holds if NO record says yes; an abstract-only record's "not found in the
    # accessible material" is the weaker sense VIII-C states for those eleven.
    ("q_lit_intro_none", r"none\s+gives a sampling distribution",
     [("docs/literature_screen.json", "records[?relevant_lunar_cpr_ice_study=true].critical_value_reported", ("none_are", "yes")),
      ("docs/literature_screen.json", "records[?relevant_lunar_cpr_ice_study=true].exceedance_rate_reported", ("none_are", "yes"))],
     "I", "no screened record reports a critical value or an exceedance rate"),
    ("q_lit_iv_none", r"none tests per-pixel\s+significance",
     [("docs/literature_screen.json", "records[?relevant_lunar_cpr_ice_study=true].critical_value_reported", ("none_are", "yes")),
      ("docs/literature_screen.json", "records[?relevant_lunar_cpr_ice_study=true].exceedance_rate_reported", ("none_are", "yes"))],
     "VIII", "per-pixel significance and exceedance rate are recorded per study; "
             "'an interval on a detected area' has no field of its own"),
    ("q_lit_one_of_25", r"none reports one for a DFSAR product",
     [("docs/literature_screen.json", "counts.claims_yes.measured_ENL_reported",
       ("count", 1)),
      ("docs/literature_screen.json",
       "records[?relevant_lunar_cpr_ice_study=true].measured_ENL_reported", ("yes_only_for_id", 2))],
     "VIII", "exactly one record reports a measured ENL, and it is Spudis et al. "
             "(Mini-RF, id 2), not a DFSAR study"),
    ("q_lit_none_crit", r"none reports a per-pixel critical value",
     [("docs/literature_screen.json", "records[?relevant_lunar_cpr_ice_study=true].critical_value_reported", ("none_are", "yes")),
      ("docs/literature_screen.json", "records[?relevant_lunar_cpr_ice_study=true].exceedance_rate_reported", ("none_are", "yes"))],
     "VIII", None),
    ("q_cardanus_uniformly", r"do not\s+agree uniformly",
     [("docs/published_moments.json", "craters[?name=Cardanus E].N_from_skewness",
       ("rounds_to", "7.49")),
      ("docs/published_moments.json", "craters[?name=Cardanus E].N_from_kurtosis",
       ("rounds_to", "9.12"))],
     "VI", "'Cardanus E spans 7.49--9.12'"),
]

#: Quantifier sentences that are not claims about an array: algebraic
#: identities, definitions of method, scope statements, conditionals. Each is
#: listed with the reason, so a NEW quantified sentence is flagged until
#: somebody decides which kind it is. (anchor, reason)
QUANTIFIER_EXEMPT = [
    (r"every absence claim is scoped", "editorial: the contributions list"),
    (r"Every statistic on the delivered product", "method: which mask a statistic uses"),
    (r"Each is stored as an unsigned 16-bit", "label field (UnsignedLSB2), not a number claim"),
    (r"contains unity for every\s+pixel", "algebraic: c <= 1 <= 1/c for every amplitude pair"),
    (r"identically, \$\\mathrm\{CPR\}_a>1\$ is empty", "algebraic: CPR_a = c <= 1"),
    (r"every pixel the screen rejects", "algebraic: the complement argument"),
    (r"Each\s+pixel is bound individually", "algebraic: Eq. (6) per Stokes vector"),
    (r"every downstream statistic is a frame-wide summary", "editorial scope"),
    (r"identical estimator", "method: the same estimator on both arms"),
    (r"identical pipeline", "method: the benchmark uses the production pipeline"),
    (r"moments of each intensity", "model statement about an ENL"),
    (r"would each explain", "conditional: either explanation suffices"),
    (r"would each have failed it", "conditional: falsification criteria"),
    (r"zero algebraically for every\s+admissible input", "algebraic; G31 checks it on corrupted inputs"),
    (r"all languages and document types", "search protocol, literature_search.json"),
    (r"Every result from", "scope: conditional on the amplitude reading"),
    (r"in all sections", "disclosure statement"),
    (r"none an ISRO statement", "editorial: the provenance of the three facts"),
    (r"every power of a low-variance variable", "mathematical: moment ENL of x^k"),
    (r"none recovers the per-pixel sign", "algebraic: the sign of S3 is not in the powers"),
    (r"moments are each invertible", "mathematical: F(2N,2N) moments are monotone in N"),
    (r"0\.45\\,\\% of all cells", "'of all cells' is the denominator of a measured fraction"),
    (r"every\s+selected cell holding a measured CPR below the\s+critical value",
     "restates q_selected_below_130 in the conclusion; checked there"),
]
