"""
manuscript_audit_table.py -- the map from every load-bearing figure the
manuscript prints to the artifact key it must come from.

Imported by audit_manuscript_numbers.py, which does the reading and the
comparing. The table lives in its own file because it is the part a reviewer
argues with: one row per printed figure, in the order the manuscript prints
them, each naming the file and the key.

    (id, printed literal, artifact, dotted key, section, note)

`artifact=None` marks a figure with no artifact expected -- a closed form
checked under DERIVED, a value from the cited literature, or a run parameter.
Those are reported NO SOURCE unless the note says why, because "no artifact"
is the finding this audit exists to surface.

Rounding: a row is compared at the precision the manuscript prints. Where the
printed value and the artifact disagree only in the last digit because the
manuscript computed from a rounded input, the row stays and the MISMATCH is
reported -- the audit does not get to choose which of the two is right.
"""
from __future__ import annotations

import json
import math
from pathlib import Path

_BASE = Path(__file__).resolve().parents[2]


def _j(rel):
    return json.loads((_BASE / rel).read_text(encoding="utf-8"))

#: Rows retired by the third revision (2026-09-23), with the reason. Kept as
#: a record so a literal that comes back is noticed rather than silently
#: re-audited against a key nobody re-checked.
RETIRED = {
    "obs_duration": "107.106 s (II-A now prints the UTC start/stop only)",
    "f2_line": "the F2 frame pixel 1120.3 / 3676.9",
    "f2_sample": "the F2 frame pixel 1120.3 / 3676.9",
    "rms_resid": "the float32 rms residual (III-B prints the maximum only)",
    "putrevu_az": "Putrevu SLC spacing 0.55 m (C12: geometry compressed to one sentence)",
    "putrevu_rg": "Putrevu SLC spacing 9.6 m (C12)",
    "putrevu_rho_lo": "the 0.29-0.35 altitude range of the bound (C12)",
    "putrevu_rho_hi": "the 0.29-0.35 altitude range of the bound (C12)",
    "kc_sigma": "the 0.02-point sampling error of the shared-texture check (C13)",
    "t3_264_crit": "2.64 -- now printed to three decimals, keyed as sens_crit_264",
    "t3_530_crit": "1.96 -- now printed to three decimals, keyed as sens_crit_530",
    "t3_622_crit": "1.86 -- now printed to three decimals, keyed as sens_crit_622",
    "cr_0": "17.6, the rho = 0 Monte Carlo row -- V-C now prints the analytic F value 17.5",
}

#: Rows retired by v11 (council work order, 2026-09-23 18:00).
RETIRED_V11 = {
    "gen_crossing": "8.6e-5, the second acquisition's crossing agreement (v11 cites the replication, not the figure)",
    "quadrature": "the 1.7 deg instrumental offset (v11 drops it)",
    "s3_effect": "the 0.04 % effect on S3 (v11 drops it)",
    "pb_field_az": "the patch-bias field correlations (v11 keeps only the 6.61 / 6.01 result)",
    "pb_field_rg": "as pb_field_az",
    "pb_lag_az": "as pb_field_az",
    "pb_lag_rg": "as pb_field_az",
    "pb_unc": "the 6.00 uncorrelated control",
    "shaped": "the mildly shaped spectrum 7.38 (v11 keeps the Hamming 4.07)",
    "t3_264_n": "the V-A sensitivity sentence (v11 keeps only the 2.07 -> 1.64 range)",
    "t3_264_p07": "as t3_264_n",
    "t3_530_n": "as t3_264_n",
    "t3_530_p07": "as t3_264_n",
    "t3_583_p07": "as t3_264_n",
    "t3_622_raw": "as t3_264_n",
    "t3_622_n": "as t3_264_n",
    "t3_622_p07": "as t3_264_n",
    "sens_crit_264": "as t3_264_n",
    "sens_crit_530": "as t3_264_n",
    "sens_crit_622": "as t3_264_n",
    "power_15": "the 27 / 56 / 88 % power sentence (v11 keeps 16.4 and 5 %)",
    "f2_peak_eff": "the N = 5 illustration 2.52 / 7.38 (v11 drops it)",
    "f2_peak_raw": "as f2_peak_eff",
    "f2_max_p95": "the correlated-F p95 2.73 and exceedance count (v11 keeps the median and FWE)",
    "f2_count": "as f2_max_p95",
    "f2_count_se": "as f2_max_p95",
    "putrevu_relsd": "the Putrevu dispersion check (v11 drops the paragraph)",
    "putrevu_n": "as putrevu_relsd",
    "putrevu_floor": "as putrevu_relsd",
    "putrevu_rho": "as putrevu_relsd",
    "putrevu_alt_n": "as putrevu_relsd",
    "tail_p99": "the 0.86 / 0.81 block tail ratios (v11 reports model ranks and held-out rates)",
    "minirf_base_res": "the 150 m baseline resolution (v11 drops it)",
    "win_n_lo": "'about 100 to 120' became the exact medians 97 and 122 (rows win97, win122)",
    "win_n_hi": "as win_n_lo",
}

#: Rows retired by v14 (final pass, 2026-09-23): each literal verified absent
#: from the v14 .tex, or superseded by the named v14 row.
RETIRED_V14 = {
    'bias_n4': "the benchmark's absolute bias at N = 4 (0.68); v14 IV keeps the relative 'about 16 % high'",
    'bias_n12': 'as bias_n4, at N = 12 (1.86)',
    'pb_16': 'the correlated patch-bias modes 6.61 / 6.01 (v14 drops the patch-bias sentence)',
    'pb_32': 'as pb_16',
    'n_sc': 'the frame-wide SC / OC moment ENLs 12.7 / 18.1 (v14 prints the block medians 14.8 / 25.6)',
    'n_oc': 'as n_sc',
    'crit_lo': 'the V-A critical-value range 1.64-2.07 over the bootstrap interval (v14 drops it; G32 retargeted)',
    'crit_hi': 'as crit_lo',
    'exceed_lo': 'the exceedance range 11.8-20.8 % over the same interval (as crit_lo)',
    'exceed_hi': 'as exceed_lo',
    'bg_05': 'the background-0.5 exceedance 3.7 % (v14 keeps the 0.7 background and the 1.12 case)',
    'f2_max_med': 'the correlated-F median maximum 1.91 (v14 reports the complex-field null only)',
    'cr_05': 'the Lee correlated-ratio row at |rho| = 0.5, 14.1 % (v14 prints the 0 and 0.9 ends)',
    'win_r95': "the 15 x 15 windows' p95 ratio 1.02 (v14 reports the 64 x 64 blocks)",
    'm_min_07': '0.176, the minimum DOP at CPR 0.7 (v14 prints the populations at DOP 0.20 / 0.30)',
    'null14_lo': 'the joint_calibration N = 14 ranges (v14 re-reports from joint_power_curve.json, strict band)',
    'band14_lo': 'as null14_lo',
    'cpr07_d20': 'the N = 14 ice-free rates 1.6 / 0.8 (v14 prints the N = 38 rates 1.8 / 0.3, v14_cpr07_*)',
    'cpr07_d30': 'as cpr07_d20',
    'gate_qual_lo': 'the joint_calibration gate-pass ranges (v14 re-keys them to joint_power_curve arm A, v14_gate*)',
    'gate_d20_lo': 'as gate_qual_lo',
    'gate_d20_hi': 'as gate_qual_lo',
    'gate_d30': 'as gate_qual_lo',
    'ho_med5': 'the per-block median held-out rates 1.39 / 4.42 (v14 prints the pooled rates with block-bootstrap CIs)',
    'ho_med10': 'as ho_med5',
    'win97': 'the 15 x 15 window medians 97 / 122 (v14 reports the 64 x 64 blocks)',
    'win122': 'as win97',
    'f2_fwe': "86.3 (v14 prints '85--86 % (two runs)', v14_f2_fwe_lo and f2_fwe_int)",
    'f2_clus5': 'the 67.5 % five-pixel cluster rate (v14 drops cluster sizes)',
    'f2_corrf_fwe': 'the correlated-F crater-level 52 % (v14 reports the complex-field null only)',
    'swath_max': 'the swath maximum 5.341e-2 (v14 VIII prints the closed-form cap 4.261e-3 only)',
    'tex_f_4': "'22.5' passed on IV-B's unrelated bootstrap range '10.7--22.5'; v14 V-D prints 22.4, the F rate at the unrounded ENL 9.337 (v14_tex_f_4)",
}

#: Quantified rows retired or re-anchored by v14.
RETIRED_QUANTIFIED_V14 = {
    'q_half_all_cells': "'half of all cells' is gone from v14 V-A",
    'q_v11_concl_selected': "the conclusion now reads 'every cell the joint criterion selects has a measured CPR below 1.299' (q_v14_concl_selected)",
    'q_v11_not_every_block': "'not for every one' is gone; v14 prints the counts 13 / 11 / 11 against 47-51",
    'q_v11_one_pass': "the flagged 'All results come from one pass' is gone from v14",
    'q_v11_identity_every_cell': "reworded 'an identity that holds on every cell' (q_v14_identity_every_cell)",
    'q_v11_each_block': "reworded 'the two channels in each block' (q_v14_each_block)",
}

AUDIT = [
    # =================================================================
    # II. THE PRODUCT, AND THE TWO MASKS
    # =================================================================
    ("looks21", "21", "docs/enl_predictions.json",
     "predictions[0].declared.azimuth_looks", "II", "label field"),
    ("look_bw", "51.016", "docs/enl_predictions.json",
     "predictions[0].declared.azimuth_look_bandwidth", "II", "label field"),
    ("bw_label", "1071.336", "docs/enl_predictions.json",
     "predictions[0].declared.total_processed_azimuth_bandwidth", "II", "label field"),
    ("prf", "3321.64", "docs/enl_predictions.json",
     "predictions[0].declared.pulse_repetition_frequency", "II", "label field"),
    ("kcal", "70.308868", "docs/enl.json",
     "label.calibration_constant", "II", "label field, sri product"),
    # III-A: the constant with its unit, and the per-channel gains
    ("kcal_db_ortho", "70.308868", "docs/dop_exclusion.json", "calibration.K_db", "III",
     "unit dB, ortho (sri) label; K = 10^(K_dB/10) is calibration.K_lin. The SLC "
     "label's 80.0 dB is a different product's constant"),
    ("gain_g_lh", "1.018", "docs/dop_exclusion.json", "gain_imbalance.LH", "III",
     "label gain imbalance, LH"),
    ("gain_g_lv", "1.001", "docs/dop_exclusion.json", "gain_imbalance.LV", "III",
     "label gain imbalance, LV"),
    ("geo_nodes", "937,296", "data/pradan/dfsar/metadata_real.json",
     "geodetic_frame.isro_geolocation_grid_agreement.nodes_compared", "II", None),
    ("geo_rms_sample", "0.2846", "data/pradan/dfsar/metadata_real.json",
     "geodetic_frame.isro_geolocation_grid_agreement.sample_residual_px.rms", "II", None),
    ("geo_rms_line", "0.4550", "data/pradan/dfsar/metadata_real.json",
     "geodetic_frame.isro_geolocation_grid_agreement.line_residual_px.rms", "II", None),
    ("psr_jaccard", "0.714", "docs/psr_validation.json",
     "jaccard", "II", "against the LOLA team's published PSR mask"),
    ("frame_px", "14,943,444", "docs/landing_sites.json",
     "search.pixels_evaluated", "II", "2258 x 6618, the full frame"),
    ("frame_km2", "9339.65", "frontend/public/analysis/faustini.json",
     "grid.frame_area_km2", "II", None),
    ("foot_px", "5,324,545", "frontend/public/analysis/faustini.json",
     "masks.footprint.pixels", "II", "ISRO sri_ma > 0"),
    ("foot_km2", "3327.84", "frontend/public/analysis/faustini.json",
     "masks.footprint.area_km2", "II", None),
    ("foot_frac", "35.63", "frontend/public/analysis/faustini.json",
     "masks.footprint.fraction", "II", "fraction stored; printed as a percentage"),
    ("valid_px", "2,337,086", "frontend/public/analysis/faustini.json",
     "masks.amplitude.pixels", "II", "(LH > 0) & (LV > 0)"),
    ("amp_km2", "1460.68", "frontend/public/analysis/faustini.json",
     "masks.amplitude.area_km2", "II", None),
    ("cov_amp", "15.64", "frontend/public/analysis/faustini.json",
     "masks.amplitude.fraction", "II", "fraction stored; printed as a percentage"),
    ("amp_over_pointed", "43.89", "frontend/public/analysis/faustini.json",
     "masks.returned_over_pointed", "II", "fraction stored; printed as a percentage"),
    ("f2_disc", "1521", "docs/f2_footprint.json",
     "disc_pixels", "II", "44 px diameter at 25 m"),
    ("cov_f2", "17.09", "docs/f2_footprint.json",
     "disc_amplitude_fraction", "II", "fraction stored; printed as a percentage"),
    ("f2_cpr", "1.95", "docs/detection_statistics.json",
     "published_reanalysis.rows[0].cpr", "II", "Sinha et al. 2026, transcribed"),

    # =================================================================
    # III. THE AMPLITUDE-ONLY DEGENERACY
    # =================================================================
    ("slc_q5", "0.89", "docs/stokes_from_slc.json",
     "results.t3a.slc_21look_boxcar5_sqrt_ratio[0]", "III",
     "5th percentile, SLC 21-look + boxcar5 sqrt(l_H/l_V)"),
    ("slc_q95", "1.18", "docs/stokes_from_slc.json",
     "results.t3a.slc_21look_boxcar5_sqrt_ratio[4]", "III", "95th percentile"),
    ("del_q5", "0.93", "docs/stokes_from_slc.json",
     "results.t3a.delivered_boxcar5_sqrt_DN2_ratio[0]", "III",
     "5th percentile, sqrt(boxcar5(DN^2)) ratio at matched ENL"),
    ("del_q95", "1.17", "docs/stokes_from_slc.json",
     "results.t3a.delivered_boxcar5_sqrt_DN2_ratio[4]", "III", "95th percentile"),
    ("x_bound", "0.2614797", None, None, "III",
     "2*artanh(0.13); closed form, checked as DERIVED below"),
    ("ceiling", "4.261e-3", "docs/degeneracy_replication.json",
     "closed_form_ceiling", "III", "tanh^2(artanh(0.13)/2)"),
    ("ceiling_full", "4.2610829e-3", "docs/degeneracy_replication.json",
     "closed_form_ceiling", "III", "the same constant to eight figures"),
    ("factor", "235", "frontend/public/analysis/sweep_grid.json",
     "crossing.factor_below_published", "III", "1.00 / measured crossing"),
    ("dop_excluded", "40.21", "docs/dop_exclusion.json",
     "excluded_percent", "III", "DOP_a >= 0.13, excluded whatever the phase"),
    ("dop_undecidable", "59.79", "docs/dop_exclusion.json",
     "undecidable_percent", "III", "the remainder; undecidable from amplitudes"),
    ("valid_px_fig", "2,337,086", "docs/dop_exclusion.json",
     "measured_pixels", "III", "the same count, recomputed in Fig. 1's own path"),
    ("max_resid_stored", "1.241e-6", "frontend/public/analysis/faustini.json",
     "cpr_dop_identity.max_abs_residual", "III", "stored float32 field"),
    ("crossing", "4.2610574e-3", "frontend/public/analysis/sweep_grid.json",
     "crossing.cpr_value", "III", "max CPR where DOP < 0.13, screened field"),
    ("crossing_rel", "5.99e-6", None, None, "III",
     "relative agreement, crossing vs closed form; DERIVED"),
    # ---- the Monte Carlo of the proxy ---------------------------------
    ("mc_N", "5", "docs/cpr_significance.json",
     "monte_carlo[0].n_looks", "III", "look count the simulator ran at"),
    ("mc_trials", "120 000", "docs/cpr_significance.json",
     "monte_carlo_run.trials_per_row", "III",
     "the run parameter, now recorded: the committed artifact reproduces "
     "bit-for-bit at --trials 120000 --coherence 0.9822"),
    ("mc_proxy_med_07", "0.00043", "docs/cpr_significance.json",
     "monte_carlo[1].amplitude_proxy.median", "III", None),
    ("mc_proxy_1db", "0.00331", "docs/cpr_significance.json",
     "monte_carlo[4].amplitude_proxy.median", "III", "1 dB imbalance"),
    ("mc_proxy_3db", "0.02922", "docs/cpr_significance.json",
     "monte_carlo[5].amplitude_proxy.median", "III", "3 dB imbalance"),
    # ---- III-D, the propagation bound ---------------------------------
    ("cpr_with_sin", "0.053411", "docs/incidence_audit.json",
     "screening_blast_radius.cpr_max_with_sin", "III", None),
    ("cpr_without_sin", "0.053852", "docs/incidence_audit.json",
     "screening_blast_radius.cpr_max_without", "III", None),
    ("dcpr_max", "1.310e-2", "docs/propagation_percentiles.json",
     "cpr.over_amplitude_mask.max", "III", None),
    ("ddop_max", "1.393e-1", "docs/propagation_percentiles.json",
     "dop.over_amplitude_mask.max", "III", None),
    ("dcpr_med", "2.3e-5", "docs/propagation_percentiles.json",
     "cpr.over_amplitude_mask.p50", "III", None),
    ("ddop_med", "1.1e-3", "docs/propagation_percentiles.json",
     "dop.over_amplitude_mask.p50", "III", None),
    # ---- III-E, the Stokes vector from the SLC ------------------------
    # III-E: the published aggregation and the per-pixel bound
    ("sinha_dop_lo", "0.10", "docs/literature_screen.json",
     "records[?id=4].aggregation_record.average_dop_range[0]", "III",
     "literature value; the quotation is recorded with it"),
    ("sinha_dop_hi", "0.13", "docs/literature_screen.json",
     "records[?id=4].aggregation_record.average_dop_range[1]", "III", None),
    ("band_hi_2dp", "1.30", "docs/stokes_from_slc.json",
     "results.invariant.t3f_coupling_band.band[1]", "III",
     "'every one with a measured CPR below 1.30'"),
    ("win_rank_corr", "0.98", "docs/stokes_from_slc.json",
     "results.t3e.180_deg.coherence_predicts_cpr.spearman", "III",
     "Spearman, (1-rho)/(1+rho) of each window's median H-V coherence against its "
     "median CPR, 20 windows"),
    ("dop_bias_n14", "7", "docs/dop_sampling_bias.json",
     "manuscript_figure.closed_form_percent", "III",
     "P(m_hat < 0.13 | DOP 0, N 14) = Beta(3/2, 13) cdf at 0.13^2; simulated 7.05 "
     "+/- 0.04 % in rows[1]"),
    ("band_lo", "0.7699", "docs/stokes_from_slc.json",
     "results.invariant.t3f_coupling_band.band[0]", "III", "(1-0.13)/(1+0.13)"),
    ("band_hi", "1.2989", "docs/stokes_from_slc.json",
     "results.invariant.t3f_coupling_band.band[1]", "III", "(1+0.13)/(1-0.13)"),
    ("slc_cells", "5,883,594", "docs/stokes_from_slc.json",
     "slc.matched_cells", "III", "21-look x 5x5 cells with both channels positive"),
    ("coh_med", "0.658", "docs/stokes_from_slc.json",
     "results.invariant.coherence.median", "III", None),
    ("coh_win_med", "0.174", "docs/stokes_from_slc.json",
     "results.invariant.coherence.per_window_summary.median", "III",
     "over the 20 most homogeneous 15x15 windows"),
    ("coh_win_min", "0.09", "docs/stokes_from_slc.json",
     "results.invariant.coherence.per_window_summary.min", "III", None),
    ("coh_win_max", "0.64", "docs/stokes_from_slc.json",
     "results.invariant.coherence.per_window_summary.max", "III", None),
    ("dop_frac", "1.50", "docs/stokes_from_slc.json",
     "results.invariant.dop_below_threshold.fraction", "III",
     "fraction stored; printed as a percentage"),
    ("dop_win_med", "11", "docs/stokes_from_slc.json",
     "results.invariant.dop_below_threshold.per_window_summary.median", "III",
     "fraction stored; printed as a percentage"),
    ("dop_win_max", "32", "docs/stokes_from_slc.json",
     "results.invariant.dop_below_threshold.per_window_summary.max", "III",
     "fraction stored; printed as a percentage"),
    ("phase_mean", "-88.3", "docs/stokes_from_slc.json",
     "results.sign.phase_evidence.circular_mean_deg", "III", None),
    ("phase_R", "0.946", "docs/stokes_from_slc.json",
     "results.sign.phase_evidence.resultant_length", "III", None),
    ("med_180", "0.21", "docs/stokes_from_slc.json",
     "results.sign.admissible_readings.180_deg", "III", "the physical sign"),
    ("med_0", "4.73", "docs/stokes_from_slc.json",
     "results.sign.admissible_readings.0_deg", "III", "its reciprocal"),
    ("joint_cond", "29.9", "docs/stokes_from_slc.json",
     "results.joint_measured.conditional.fraction", "III",
     "P(CPR>1 | DOP<0.13); fraction stored, printed as a percentage"),
    ("joint_all", "0.45", "docs/stokes_from_slc.json",
     "results.joint_measured.unconditional.fraction", "III",
     "fraction stored; printed as a percentage"),

    # =================================================================
    # IV. THE EQUIVALENT NUMBER OF LOOKS
    # =================================================================
    ("enl16_lh", "5.30", "docs/enl.json",
     "patch_sizes.16.LH.on_DN_squared.mode", "IV", "16x16 patches, delivered"),
    ("enl16_lv", "6.46", "docs/enl.json",
     "patch_sizes.16.LV.on_DN_squared.mode", "IV", None),
    ("enl_lh", "5.83", "docs/enl.json", "boxcar_gain.LH.enl_raw", "IV",
     "over the screening mask"),
    ("enl_lv", "5.14", "docs/enl.json", "boxcar_gain.LV.enl_raw", "IV", None),
    ("patches", "8,337", "docs/bootstrap_enl.json", "LH.n_patches", "IV", None),
    ("boot_lh_lo", "4.03", "docs/bootstrap_enl.json",
     "LH.enl_raw_ci_block[0]", "IV", "block bootstrap, B = 2000"),
    ("boot_lh_hi", "6.19", "docs/bootstrap_enl.json",
     "LH.enl_raw_ci_block[1]", "IV", None),
    ("boot_lv_lo", "4.38", "docs/bootstrap_enl.json",
     "LV.enl_raw_ci_block[0]", "IV", None),
    ("boot_lv_hi", "7.29", "docs/bootstrap_enl.json",
     "LV.enl_raw_ci_block[1]", "IV", None),
    ("boot_lh5_lo", "10.7", "docs/bootstrap_enl.json",
     "LH.enl_box_ci_block[0]", "IV", "after the 5x5 boxcar"),
    ("boot_lh5_hi", "22.5", "docs/bootstrap_enl.json",
     "LH.enl_box_ci_block[1]", "IV", None),
    ("boot_lv5_lo", "12.1", "docs/bootstrap_enl.json",
     "LV.enl_box_ci_block[0]", "IV", None),
    ("boot_lv5_hi", "24.8", "docs/bootstrap_enl.json",
     "LV.enl_box_ci_block[1]", "IV", None),
    ("cov_lo", "12", "docs/enl_benchmark.json",
     "synthetic.speckle_only_summary.coverage_percent_range[0]", "IV",
     "coverage of the nominally 95 % block bootstrap, synthetic speckle"),
    ("cov_hi", "26", "docs/enl_benchmark.json",
     "synthetic.speckle_only_summary.coverage_percent_range[1]", "IV", None),
    ("mode_bias", "16", "docs/enl_benchmark.json",
     "synthetic.speckle_only_summary.relative_bias_percent_median", "IV",
     "the mode estimator's relative bias on correlated speckle"),
    ("corrected_raw", "5.0", "docs/enl_benchmark.json",
     "synthetic.speckle_only_summary.raw_enl_5p83_corrected", "IV",
     "5.83 read through the measured bias"),
    ("enl32_lh", "2.64", "docs/enl.json",
     "patch_sizes.32.LH.on_DN_squared.mode", "IV", None),
    ("stat_lo", "3.3", "docs/stationarity.json", "enl_min", "IV",
     "over the four blocks with coverage"),
    ("stat_hi", "8.0", "docs/stationarity.json", "enl_max", "IV", None),
    # ---- IV-B, the control --------------------------------------------
    ("bw_measured", "1071.2", "docs/slc_multilook_control.json",
     "medians.measured_bandwidth_hz", "IV", "median across the nine windows"),
    ("bw_min", "1071.2", "docs/slc_multilook_control.json",
     "windows[*].measured_bandwidth_hz|min", "IV", "'1071.2--1071.6 Hz across the nine windows'"),
    ("bw_max", "1071.6", "docs/slc_multilook_control.json",
     "windows[*].measured_bandwidth_hz|max", "IV", None),
    ("sl_median", "1.04", "docs/slc_multilook_control.json",
     "medians.enl_single_look", "IV", "single-look intensity, answer known"),
    ("sl_min", "0.93", "docs/slc_multilook_control.json",
     "min.enl_single_look", "IV", None),
    ("sl_max", "1.12", "docs/slc_multilook_control.json",
     "max.enl_single_look", "IV", None),
    ("osamp", "3.10", "docs/slc_multilook_control.json",
     "medians.oversampling_factor", "IV", None),
    ("two_wt", "6.77", "docs/slepian_ceiling.json",
     "two_WT_asymptotic", "IV", "21 / 3.10, asymptotic"),
    ("part_ratio", "7.34", "docs/slepian_ceiling.json",
     "participation_ratio_rectangular", "IV", "exact, rectangular spectrum"),
    ("hamming", "4.07", "docs/slepian_ceiling.json",
     "enl_hamming_054", "IV", "the shape the label declares"),
    ("spatial", "4.52", "docs/slc_multilook_control.json",
     "medians.enl_spatial_21", "IV", None),
    ("subband", "9.95", "docs/slc_multilook_control.json",
     "medians.enl_subband_21", "IV", None),
    ("width_sp", "0.95", "docs/mechanism_controls.json",
     "medians.width_az_spatial", "IV", "azimuth ACF half-width, output rows"),
    ("width_sb", "2.79", "docs/mechanism_controls.json",
     "medians.width_az_subband", "IV", None),
    ("paired", "4.47", "docs/mechanism_controls.json",
     "paired_difference_subband_minus_spatial.mean", "IV", "nine windows, paired"),
    ("paired_se", "0.43", "docs/mechanism_controls.json",
     "paired_difference_subband_minus_spatial.se", "IV", None),
    ("matched", "-1.00", "docs/mechanism_controls.json",
     "paired_difference_at_matched_width.mean", "IV",
     "sub-band minus spatial once the finer arm is smoothed to the coarser width"),
    ("matched_se", "0.57", "docs/mechanism_controls.json",
     "paired_difference_at_matched_width.se", "IV", None),
    # ---- IV-C, the generality test ------------------------------------
    ("gen_looks", "39", "docs/enl_predictions.json",
     "predictions[2].declared.azimuth_looks", "IV", "2020-03-05 L-band"),
    ("gen_osamp", "2.905", "docs/enl_predictions.json",
     "predictions[2].oversampling", "IV", None),
    ("gen_reference", "13.42", "docs/enl_predictions.json",
     "predictions[2].predicted_ceiling", "IV", "registered before the product was opened"),
    ("gen_part_ratio", "14.04", "docs/slepian_ceiling.json",
     "other_products[1].participation_ratio_rectangular", "IV",
     "39 samples at oversampling 2.905"),
    ("gen_lh", "2.28", "docs/enl_generality.json",
     "measurements[4].measured_enl", "IV", None),
    ("gen_lv", "2.21", "docs/enl_generality.json",
     "measurements[5].measured_enl", "IV", None),
    ("gen_attained", "0.17", "docs/enl_generality.json",
     "measurements[4].attained_fraction", "IV", None),
    ("here_attained", "0.86", "docs/enl_generality.json",
     "measurements[0].attained_fraction", "IV", "this pass, for comparison"),
    # ---- IV-D, spatial averaging --------------------------------------
    ("lag_az", "0.838", "docs/enl.json",
     "lag_correlation.LH.azimuth_lines[0]", "IV", None),
    ("lag_rg", "0.576", "docs/enl.json",
     "lag_correlation.LH.range_samples[0]", "IV", None),
    ("eroded_px", "2,294,084", "docs/enl_estimator_spec.json",
     "masks.enl_measurement_mask.n_px", "IV", "amplitude mask eroded by 5x5"),
    ("gain_lh", "2.35", "docs/enl.json", "boxcar_gain.LH.gain", "IV", None),
    ("gain_lv", "3.84", "docs/enl.json", "boxcar_gain.LV.gain", "IV",
     "the manuscript says \"on the unrounded estimates\": 3.8449 -> 3.84"),
    ("enl5_lh", "13.72", "docs/detection_statistics.json",
     "effective_looks.screened_field.lh", "IV", None),
    ("enl5_lv", "19.77", "docs/detection_statistics.json",
     "effective_looks.screened_field.lv", "IV", None),

    # =================================================================
    # V. DETECTION STATISTICS
    # =================================================================
    ("floor38", "1.44", None, None, "V",
     "sqrt((2N-1)/(N-2)) at N = 38, ratio of relSD(R) to 1/sqrt(N); DERIVED"),
    ("floor6", "1.66", None, None, "V", "the same at N = 6; DERIVED"),
    # Table II, seven rows by five columns, at the N each row prints
    ("t2_n5_sd", "0.775", "docs/detection_statistics.json",
     "sampling_statistics.rows[0].rel_sd", "V", None),
    ("t2_n5_bias", "1.250", "docs/detection_statistics.json",
     "sampling_statistics.rows[0].bias", "V", None),
    ("t2_n5_crit", "2.978", "docs/detection_statistics.json",
     "sampling_statistics.rows[0].crit_95", "V", None),
    ("t2_n5_p07", "29.16", "docs/detection_statistics.json",
     "sampling_statistics.rows[0].p_exceed_true_cpr_0p7_percent", "V", None),
    ("t2_n5_p05", "14.48", "docs/detection_statistics.json",
     "sampling_statistics.rows[0].p_exceed_true_cpr_0p5_percent", "V", None),
    ("t2_n677_sd", "0.623", "docs/detection_statistics.json",
     "sampling_statistics.rows[1].rel_sd", "V", None),
    ("t2_n677_bias", "1.173", "docs/detection_statistics.json",
     "sampling_statistics.rows[1].bias", "V", None),
    ("t2_n677_crit", "2.525", "docs/detection_statistics.json",
     "sampling_statistics.rows[1].crit_95", "V", None),
    ("t2_n677_p07", "26.03", "docs/detection_statistics.json",
     "sampling_statistics.rows[1].p_exceed_true_cpr_0p7_percent", "V", None),
    ("t2_n677_p05", "10.75", "docs/detection_statistics.json",
     "sampling_statistics.rows[1].p_exceed_true_cpr_0p5_percent", "V", None),
    ("t2_n875_sd", "0.529", "docs/detection_statistics.json",
     "sampling_statistics.rows[2].rel_sd", "V", None),
    ("t2_n875_bias", "1.129", "docs/detection_statistics.json",
     "sampling_statistics.rows[2].bias", "V", None),
    ("t2_n875_crit", "2.244", "docs/detection_statistics.json",
     "sampling_statistics.rows[2].crit_95", "V",
     "at the N the row prints (8.75); at_measured_N gives 2.243 from the "
     "unrounded median 8.7544, and both are in the artifact"),
    ("t2_n875_p07", "23.16", "docs/detection_statistics.json",
     "sampling_statistics.rows[2].p_exceed_true_cpr_0p7_percent", "V", None),
    ("t2_n875_p05", "7.85", "docs/detection_statistics.json",
     "sampling_statistics.rows[2].p_exceed_true_cpr_0p5_percent", "V",
     "at the N the row prints; at_measured_N gives 7.84"),
    ("t2_n1372_sd", "0.405", "docs/detection_statistics.json",
     "sampling_statistics.rows[3].rel_sd", "V",
     "at the N the row prints (13.72); at_measured_N gives 0.406 from the "
     "unrounded ENL 13.7166"),
    ("n_edge", "80", "docs/detection_statistics.json",
     "derived.n_at_which_crit_equals_band_edge.N", "V",
     "'the critical value falls to 1.2989 only at N ~ 80'; 79.62"),
    ("t2_n1372_bias", "1.079", "docs/detection_statistics.json",
     "sampling_statistics.rows[3].bias", "V", None),
    ("t2_n1372_crit", "1.895", "docs/detection_statistics.json",
     "sampling_statistics.rows[3].crit_95", "V", None),
    ("t2_n1372_p07", "17.79", "docs/detection_statistics.json",
     "sampling_statistics.rows[3].p_exceed_true_cpr_0p7_percent", "V", None),
    ("t2_n1372_p05", "3.74", "docs/detection_statistics.json",
     "sampling_statistics.rows[3].p_exceed_true_cpr_0p5_percent", "V", None),
    ("t2_n1977_sd", "0.331", "docs/detection_statistics.json",
     "sampling_statistics.rows[4].rel_sd", "V", None),
    ("t2_n1977_bias", "1.053", "docs/detection_statistics.json",
     "sampling_statistics.rows[4].bias", "V", None),
    ("t2_n1977_crit", "1.698", "docs/detection_statistics.json",
     "sampling_statistics.rows[4].crit_95", "V", None),
    ("t2_n1977_p07", "13.32", "docs/detection_statistics.json",
     "sampling_statistics.rows[4].p_exceed_true_cpr_0p7_percent", "V", None),
    ("t2_n1977_p05", "1.60", "docs/detection_statistics.json",
     "sampling_statistics.rows[4].p_exceed_true_cpr_0p5_percent", "V", None),
    ("t2_n21_sd", "0.321", "docs/detection_statistics.json",
     "sampling_statistics.rows[5].rel_sd", "V", None),
    ("t2_n21_bias", "1.050", "docs/detection_statistics.json",
     "sampling_statistics.rows[5].bias", "V", None),
    ("t2_n21_crit", "1.671", "docs/detection_statistics.json",
     "sampling_statistics.rows[5].crit_95", "V", None),
    ("t2_n21_p07", "12.59", "docs/detection_statistics.json",
     "sampling_statistics.rows[5].p_exceed_true_cpr_0p7_percent", "V", None),
    ("t2_n21_p05", "1.35", "docs/detection_statistics.json",
     "sampling_statistics.rows[5].p_exceed_true_cpr_0p5_percent", "V", None),
    ("t2_n38_sd", "0.234", "docs/detection_statistics.json",
     "sampling_statistics.rows[6].rel_sd", "V", None),
    ("t2_n38_bias", "1.027", "docs/detection_statistics.json",
     "sampling_statistics.rows[6].bias", "V", None),
    ("t2_n38_crit", "1.462", "docs/detection_statistics.json",
     "sampling_statistics.rows[6].crit_95", "V", None),
    ("t2_n38_p07", "6.11", "docs/detection_statistics.json",
     "sampling_statistics.rows[6].p_exceed_true_cpr_0p7_percent", "V", None),
    ("t2_n38_p05", "0.14", "docs/detection_statistics.json",
     "sampling_statistics.rows[6].p_exceed_true_cpr_0p5_percent", "V", None),
    # Table III, the sensitivity rows
    # power
    ("power_1299", "16.4", "docs/detection_statistics.json",
     "sampling_statistics.power_at_operating_point.rows[1].power_percent", "V",
     "at the largest true CPR the DOP condition admits"),
    ("power_20", "56", "docs/detection_statistics.json",
     "sampling_statistics.power_at_operating_point.rows[3].power_percent", "V", None),
    ("power_30", "88", "docs/detection_statistics.json",
     "sampling_statistics.power_at_operating_point.rows[4].power_percent", "V", None),
    # background range
    ("bg_04", "1.0", "docs/detection_statistics.json",
     "derived.p_exceed_at_operating_point.rows[0].p_exceed_percent", "V",
     "P(R > 1) at N = 13.72, true CPR 0.4"),
    ("bg_08", "28", "docs/background_cpr_sweep.json", "rows[5].fp_percent", "V", None),
    ("bg_09", "39", "docs/background_cpr_sweep.json", "rows[6].fp_percent", "V", None),
    # V-B, the crater maximum
    ("corr_area", "61.42", "docs/cpr_significance.json",
     "effective_samples.area_all_lags", "V", "px per independent sample"),
    ("f2_eff", "25", "docs/cpr_significance.json",
     "effective_samples.f2_effective_samples", "V", "1521 px / 61.42"),
    ("f2_amp_px", "260", "docs/f2_maximum.json",
     "disc.amplitude_pixels", "V", "of the 1521-pixel disc"),
    # V-C, in what sense the rates are upper bounds
    ("f_n14_07", "17.5", "docs/detection_statistics.json",
     "derived.f_exceedance_N14_cpr0p7_percent", "V",
     "the analytic F(28, 28) value at CPR 0.7, 17.545; the rho = 0 Monte Carlo row "
     "of correlated_ratio.json reads 17.58 and is no longer printed"),
    ("cr_08", "6.3", "docs/correlated_ratio.json", "rows[2].fp_percent", "V", None),
    ("cr_09", "1.9", "docs/correlated_ratio.json", "rows[3].fp_percent", "V", None),
    ("circ_corr", "0.50", "docs/stokes_from_slc.json",
     "results.t3d_180.corr_sc_oc", "V",
     "circular-channel INTENSITY correlation |corr(SC, OC)| over the frame -- not "
     "the field coherence gamma_c (third review M7; gamma_c is in "
     "stokes_from_slc.json::coherence_by_gate)"),
    ("blocks", "109", "docs/stokes_from_slc.json",
     "results.t3e.blocks_64x64.n_selected", "V", "64x64 blocks below the 10th CV pct"),
    ("tail_p95", "0.86", "docs/stokes_from_slc.json",
     "results.t3e.180_deg.blocks_64x64_summary.ratio_p95_median", "V",
     "empirical / F, within blocks"),
    ("wc_nu8", "18.8", "docs/kclutter_within_cell.json",
     "rows[1].exceed_percent", "V", "within-cell texture, order 8"),
    ("win_corr", "0.14", "docs/stokes_from_slc.json",
     "results.t3e.180_deg.windows_15x15_summary.corr_median", "V",
     "circular-channel INTENSITY correlation in the 20 windows"),
    ("win_r99", "0.98", "docs/stokes_from_slc.json",
     "results.t3e.180_deg.windows_15x15_summary.ratio_p99_median", "V", None),
    ("f2_eff", "24.8", "docs/detection_statistics.json",
     "derived.effective_samples_f2_disc.effective_samples", "V", "1521 / 61.42"),
    ("wc_nu4", "19.7", "docs/kclutter_within_cell.json",
     "rows[4].exceed_percent", "V", "order 4"),
    ("wc_base", "17.5", "docs/kclutter_within_cell.json",
     "rows[0].exceed_percent", "V",
     "no texture at N = 14, the same draw the textured rows use; the 17.8 of "
     "Table II is N = 13.72 and is a different row"),
    ("wc_enl8", "11.2", "docs/kclutter_within_cell.json",
     "rows[1].enl_of_textured_intensity", "V", None),
    ("wc_enl4", "9.3", "docs/kclutter_within_cell.json",
     "rows[4].enl_of_textured_intensity", "V",
     "order 4, INDEPENDENT per look -- the row whose exceedance is the 19.7 "
     "quoted beside it. rows[6] (lag-one 0.8) gives 5.05 and belongs to a "
     "different correlation setting"),
    ("joint_marginal", "17.5", "docs/joint_criterion.json",
     "marginal_fp_percent_analytic_F", "V", None),

    # =================================================================
    # VI. MODEL-CONSISTENCY CHECK ON PUBLISHED DATA
    # =================================================================
    ("pm_med_sigma", "8.75", "docs/published_moments.json",
     "median_N_from_dispersion", "VI", None),
    ("pm_med_skew", "9.08", "docs/published_moments.json",
     "median_N_from_skewness", "VI", None),
    ("pm_med_kurt", "9.17", "docs/published_moments.json",
     "median_N_from_kurtosis", "VI", None),
    # pm_exceed was here. Section VI no longer prints "at N = 8.75 the model
    # gives an exceedance of 23.16 %"; the only remaining occurrence of the
    # literal is Table II's 8.75 row, audited as t2_n875_p07 against
    # detection_statistics. published_moments.json still computes the same
    # figure under consequence_at_median_dispersion_N, unprinted.
    # =================================================================
    # v11 (council work order, Task 0): the joint rule as a test, the gate,
    # the F2 null, the held-out tails, the spectrum, the second pass
    # =================================================================
    ("size14", "3.6", "docs/joint_calibration.json", "summaries.N14.size_percent", "V",
     "max over CPR 1.00, DOP 0/0.05/0.10/0.13 of P(joint), N = 14, 1e5 trials"),
    ("size38", "13", "docs/joint_calibration.json", "summaries.N38.size_percent", "V", None),
    ("null14_hi", "3.6", "docs/joint_calibration.json", "summaries.N14.null_selection_range_percent[1]", "V", None),
    ("band14_hi", "3.6", "docs/joint_calibration.json", "summaries.N14.band_1p1_1p2_selection_range_percent[1]", "V", None),
    ("ratio14", "13", "docs/joint_calibration.json", "summaries.N14.max_band_over_null_same_dop_excess_percent", "V",
     "max in-band/null ratio at the same DOP, as an excess"),
    ("ratio38", "31", "docs/joint_calibration.json", "summaries.N38.max_band_over_null_same_dop_excess_percent", "V", None),
    ("gate_before", "60", "docs/joint_calibration.json", "summaries.N14.gate_effect_cpr1p1_dop0p10.p_cpr_gt_1_percent", "V",
     "CPR 1.1, DOP 0.10: P(R > 1)"),
    ("gate_after", "3.4", "docs/joint_calibration.json", "summaries.N14.gate_effect_cpr1p1_dop0p10.p_joint_percent", "V",
     "and with the gate"),
    ("gate_qual_hi", "7.1", "docs/joint_calibration.json", "summaries.N14.dop_gate_pass_qualifying_range_percent[1]", "III", None),
    ("mhat_med14", "0.29", "docs/dop_sampling_bias.json", "rows[1].median_sample_dop", "III",
     "median sample DOP of an unpolarized population, N = 14"),
    ("mean_dop_75", "75", "docs/dop_sampling_bias.json",
     "mean_sample_dop_unpolarized.N_where_mean_is_0p13", "III", "E[m_hat] = 0.13 at N = 75.09"),
    ("mean_dop_127", "127", "docs/dop_sampling_bias.json",
     "mean_sample_dop_unpolarized.N_where_mean_is_0p10", "III", "E[m_hat] = 0.10 at N = 127.07"),
    ("sigma_amp", "-20.4", "docs/calibration_example.json",
     "scene_example.amplitude_reading_with_G_db", "III", "K, G_LH, sin(theta) once"),
    ("sigma_int", "-47.8", "docs/calibration_example.json",
     "scene_example.intensity_reading_with_G_db", "III", None),
    ("gain_dop_lo", "1.03", "docs/phase_gain_perturbation.json",
     "gain_rows[?gain_error_db=-0.5].dop_below_percent", "III", None),
    ("gain_dop_hi", "1.74", "docs/phase_gain_perturbation.json",
     "gain_rows[?gain_error_db=0.5].dop_below_percent", "III", None),
    ("gain_joint_lo", "-33", "docs/phase_gain_perturbation.json",
     "gain_rows[?gain_error_db=-0.5].joint_relative_change", "III", "relative change, percent"),
    ("gain_joint_hi", "18", "docs/phase_gain_perturbation.json",
     "gain_rows[?gain_error_db=0.5].joint_relative_change", "III", None),
    ("phase_joint_max", "0.002", "docs/phase_gain_perturbation.json",
     "phase_rows[*].joint_change_pp|max", "III", "at most 0.002 percentage points at +/-5 deg"),
    ("gamma_out", "0.13", "docs/stokes_from_slc.json",
     "results.coherence_by_gate.outside_gate.gamma_c.median", "V", None),
    ("gamma_in", "0.07", "docs/stokes_from_slc.json",
     "results.coherence_by_gate.inside_gate.gamma_c.median", "V", None),
    ("ident_res", "6e-16", "docs/stokes_from_slc.json",
     "results.coherence_by_gate.identity.max_abs_residual", "V", None),
    ("blk_nsc", "14.8", "docs/stokes_from_slc.json",
     "results.t3e.180_deg.blocks_64x64_summary.n_sc_median", "V", None),
    ("blk_noc", "25.6", "docs/stokes_from_slc.json",
     "results.t3e.180_deg.blocks_64x64_summary.n_oc_median", "V", None),
    ("cnt107", "107", "docs/stokes_from_slc.json",
     "results.t3e.180_deg.two_channel_models.blocks_64x64.p95.closest_model_counts.unequal", "V", None),
    ("cnt104", "104", "docs/stokes_from_slc.json",
     "results.t3e.180_deg.two_channel_models.blocks_64x64.p95.ordering_counts.empirical <= unequal <= equal_low_N",
     "V", None),
    ("ho_med1", "0.10", "docs/stokes_from_slc.json",
     "results.t3e.180_deg.tail_calibration.held_out_rejection.1pct.median_over_blocks", "V", None),
    ("ho_pool1", "0.44", "docs/stokes_from_slc.json",
     "results.t3e.180_deg.tail_calibration.held_out_rejection_pooled.1pct", "V", None),
    ("ho_pool5", "2.31", "docs/stokes_from_slc.json",
     "results.t3e.180_deg.tail_calibration.held_out_rejection_pooled.5pct", "V", None),
    ("ho_pool10", "5.47", "docs/stokes_from_slc.json",
     "results.t3e.180_deg.tail_calibration.held_out_rejection_pooled.10pct", "V", None),
    ("ho_above1", "13", "docs/stokes_from_slc.json",
     "results.t3e.180_deg.tail_calibration.blocks_above_nominal.1pct", "V", None),
    ("ho_above5", "11", "docs/stokes_from_slc.json",
     "results.t3e.180_deg.tail_calibration.blocks_above_nominal.5pct", "V", None),
    ("ho_above10", "11", "docs/stokes_from_slc.json",
     "results.t3e.180_deg.tail_calibration.blocks_above_nominal.10pct", "V", None),
    ("ho_worst1", "7.1", "docs/stokes_from_slc.json",
     "results.t3e.180_deg.tail_calibration.worst_block_rejection.1pct", "V", None),
    ("ho_worst5", "12.4", "docs/stokes_from_slc.json",
     "results.t3e.180_deg.tail_calibration.worst_block_rejection.5pct", "V", None),
    ("cv_pct", "10", "docs/stokes_from_slc.json", "results.t3e.blocks_64x64.cv_percentile", "V",
     "'the lowest 10 %'"),
    ("tex_f_8", "20.3", "docs/detection_statistics.json",
     "derived.f_exceedance_at_textured_enl[0].p_exceed_true_cpr_0p7_percent_at_printed_enl", "V",
     "F at the textured field's printed moment ENL 11.2"),
    ("f2_enl145", "14.5", "docs/f2_maximum.json", "complex_field.look_calibration.4.boxcar_mode_enl",
     "V", "L = 4 looks"),
    ("f2_fwe_int", "86", "docs/f2_maximum.json", "complex_field.true_cpr_1.fwe_p_max_gt_crit", "I", None),
    ("f2_fwe_se", "0.3", "docs/f2_maximum.json", "complex_field.true_cpr_1.fwe_se", "V", None),
    ("f2_fwe07", "39.4", "docs/f2_maximum.json", "complex_field.true_cpr_0p7.fwe_p_max_gt_crit", "V", None),
    ("f2_fwe07_se", "0.5", "docs/f2_maximum.json", "complex_field.true_cpr_0p7.fwe_se", "V", None),
    ("tex_mode5", "3.2", "docs/enl_interval_validation.json",
     "rows[?true_N=5&texture=order 8&patch_px=16].estimate_median", "IV", None),
    ("tex_mode14", "5.2", "docs/enl_interval_validation.json",
     "rows[?true_N=14&texture=order 8&patch_px=16].estimate_median", "IV", None),
    ("tex_mode21", "5.9", "docs/enl_interval_validation.json",
     "rows[?true_N=21&texture=order 8&patch_px=16].estimate_median", "IV", None),
    ("tex_mode38", "6.6", "docs/enl_interval_validation.json",
     "rows[?true_N=38&texture=order 8&patch_px=16].estimate_median", "IV", None),
    ("b2d16_lo", "19", "docs/enl_interval_validation.json",
     "rows[?texture=off&patch_px=16].coverage.block2d_percentile.95.coverage|min", "IV", None),
    ("b2d16_hi", "26", "docs/enl_interval_validation.json",
     "rows[?texture=off&patch_px=16].coverage.block2d_percentile.95.coverage|max", "IV", None),
    ("b2d32_lo", "98", "docs/enl_interval_validation.json",
     "rows[?texture=off&patch_px=32].coverage.block2d_percentile.95.coverage|min", "IV", None),
    ("b2d32_hi", "100", "docs/enl_interval_validation.json",
     "rows[?texture=off&patch_px=32].coverage.block2d_percentile.95.coverage|max", "IV", None),
    ("bias16_lo", "15", "docs/enl_interval_validation.json",
     "rows[?texture=off&patch_px=16].relative_bias_median|min", "IV", None),
    ("bias16_hi", "16", "docs/enl_interval_validation.json",
     "rows[?texture=off&patch_px=16].relative_bias_median|max", "IV", None),
    ("bias32_lo", "3", "docs/enl_interval_validation.json",
     "rows[?texture=off&patch_px=32].relative_bias_median|min", "IV", None),
    ("bias32_hi", "5", "docs/enl_interval_validation.json",
     "rows[?texture=off&patch_px=32].relative_bias_median|max", "IV", None),
    ("param_lo", "88", "docs/enl_interval_validation.json",
     "summary_texture_off.parametric_neyman.95.min", "IV", None),
    ("param_hi", "98", "docs/enl_interval_validation.json",
     "summary_texture_off.parametric_neyman.95.max", "IV", None),
    ("spec_med", "7.13", "docs/mechanism_spec.json", "expected_looks_from_measured_spectrum.median",
     "IV", None),
    ("spec_lo", "6.88", "docs/mechanism_spec.json", "expected_looks_from_measured_spectrum.range[0]",
     "IV", None),
    ("spec_hi", "7.20", "docs/mechanism_spec.json", "expected_looks_from_measured_spectrum.range[1]",
     "IV", None),
    ("sb_enl", "12.8", "docs/mechanism_spec.json", "subband_powers.equal_power_enl_median", "IV", None),
    ("sb_cv", "0.80", "docs/mechanism_spec.json", "subband_powers.cv_median", "IV", None),
    ("gen_slc39", "6.25", "docs/enl_L_20200305_full.json",
     "candidate_causes.where_the_looks_are_lost.slc_39_line_average_median", "IV", None),
    ("gen_pr", "13.75", "docs/enl_L_20200305_full.json",
     "candidate_causes.where_the_looks_are_lost.slc_participation_ratio_measured_spectrum", "IV", None),
    ("minirf_zoom_looks", "8", "docs/published_moments.json",
     "mode_table.zoom.nominal_looks", "VI", "presence check only; small integer"),
    ("minirf_effective", "6.7", "docs/published_moments.json",
     "mode_table.effective_looks_reported.value", "VI",
     "Spudis et al. 2013, attributed to unpublished analysis"),

    # =================================================================
    # VII-VIII. THE ZERO, THE SCOPE, THE SEARCH
    # =================================================================
    ("scope_40", "40", "docs/dop_exclusion.json",
     "excluded_percent", "VIII", "rounded in the scope table"),
    ("lit_relevant", "25", "docs/literature_search.json",
     "counts.relevant", "VIII", "presence check only; small integer"),
    # =================================================================
    # v14 (final pass, 2026-09-23): the Task 0.3 literals, keyed
    # =================================================================
    ('v14_strict38_lo', '12.8', 'docs/joint_power_curve.json',
     'summary.A.by_N[?N=38].strict_band.power_min_percent', 'V', "strict band: population DOP < 0.13 only ('DOP 0.13' and 'CPR 1.299 DOP min 0.1301' dropped)"),
    ('v14_strict38_hi', '14.3', 'docs/joint_power_curve.json',
     'summary.A.by_N[?N=38].strict_band.power_max_percent', 'V', None),
    ('v14_size38', '13.2', 'docs/joint_power_curve.json',
     'summary.A.by_N[?N=38].size_percent', 'V', None),
    ('v14_size38_abs', '13', 'docs/joint_power_curve.json',
     'summary.A.by_N[?N=38].size_percent', 'I', "abstract and conclusion '13 %'"),
    ('v14_strict14_lo', '3.5', 'docs/joint_power_curve.json',
     'summary.A.by_N[?N=14].strict_band.power_min_percent', 'V', None),
    ('v14_strict14_hi', '3.6', 'docs/joint_power_curve.json',
     'summary.A.by_N[?N=14].strict_band.power_max_percent', 'V', None),
    ('v14_size14', '3.6', 'docs/joint_power_curve.json',
     'summary.A.by_N[?N=14].size_percent', 'V', None),
    ('v14_strict_excess', '41', 'docs/joint_power_curve.json',
     'summary.A.by_N[?N=38].strict_band.max_excess_over_null_same_dop_percent', 'V', "'exceeds the rate at CPR 1.00 and the same DOP by at most 41 %': ratio 1.408"),
    ('v14_size_first_A', '19', 'docs/joint_power_curve.json',
     'summary.A.first_N_size_exceeds_5pct', 'V', None),
    ('v14_size_first_B_lo', '20', 'docs/joint_power_curve.json',
     'summary.B.first_N_size_within_2se_of_5pct', 'V', "'20--21 with texture': 4.99 +/- 0.07 % at N = 20, 5.35 % at 21"),
    ('v14_size_first_B_hi', '21', 'docs/joint_power_curve.json',
     'summary.B.first_N_size_exceeds_5pct', 'V', None),
    ('v14_gate14_lo', '5.6', 'docs/joint_power_curve.json',
     'arms.A.cells[?N=14&kind=null].p_dop_below.percent|min', 'III', "the DOP gate's pass rate over the null populations, arm A"),
    ('v14_gate14_hi', '7.2', 'docs/joint_power_curve.json',
     'arms.A.cells[?N=14&kind=null].p_dop_below.percent|max', 'III', None),
    ('v14_gate38_lo', '16', 'docs/joint_power_curve.json',
     'arms.A.cells[?N=38&kind=null].p_dop_below.percent|min', 'III', None),
    ('v14_gate38_hi', '27', 'docs/joint_power_curve.json',
     'arms.A.cells[?N=38&kind=null].p_dop_below.percent|max', 'III', None),
    ('v14_gate14_d20', '4.2', 'docs/joint_power_curve.json',
     'arms.A.cells[?N=14&pop_dop=0.2].p_dop_below.percent|max', 'III', 'CPR 0.7 and 0.9 at DOP 0.20 (4.207, 4.217)'),
    ('v14_gate38_d20_lo', '7.9', 'docs/joint_power_curve.json',
     'arms.A.cells[?N=38&pop_dop=0.2].p_dop_below.percent|min', 'III', None),
    ('v14_gate38_d20_hi', '8.0', 'docs/joint_power_curve.json',
     'arms.A.cells[?N=38&pop_dop=0.2].p_dop_below.percent|max', 'III', None),
    ('v14_cpr07_d30_38', '0.3', 'docs/joint_power_curve.json',
     'arms.A.cells[?N=38&population=ice-free CPR 0.7 DOP 0.30].p_joint.percent', 'V', None),
    ('v14_dr_texB_lo', '5.9', 'docs/decision_rule.json',
     'summary.B_N14.oracle.cpr_test_size_percent', 'V', 'texture oracle, CPR component: 5.95 at N = 14 (1190 of 20 000), 6.12 at 38, 6.295 at 100'),
    ('v14_dr_texB_hi', '6.3', 'docs/decision_rule.json',
     'summary.B_N100.oracle.cpr_test_size_percent', 'V', None),
    ('v14_iut_onset_lo', '218', 'docs/decision_rule.json',
     'iut_onset.last_N_without_region', 'V', "abstract and conclusion 'no rejection region through 218 looks'"),
    ('v14_iut_onset_hi', '254', 'docs/decision_rule.json',
     'iut_onset.first_N_with_region', 'V', None),
    ('v14_prod_cpr1', '3703', 'docs/decision_rule.json',
     'product.20200808.cpr_test_rejects', 'V', None),
    ('v14_prod_dop1', '66,025', 'docs/decision_rule.json',
     'product.20200808.dop_test_rejects', 'V', None),
    ('v14_prod_sinha1', '26,462', 'docs/decision_rule.json',
     'product.20200808.sinha_rule_selects', 'V', None),
    ('v14_prod_sinha2', '24', 'docs/decision_rule.json',
     'product.20200305.sinha_rule_selects', 'V', None),
    ('v14_nhat_frame', '17.4', 'docs/decision_rule.json',
     'product.20200808.local_N_hat.median', 'V', 'per cell over the whole frame, 31 x 31 windows'),
    ('v14_lr_blocks', '39.4', 'docs/enl_logratio.json',
     'pass_20200808.blocks_64x64.N_logratio.median', 'V', None),
    ('v14_lr_blocks_abs', '39', 'docs/enl_logratio.json',
     'pass_20200808.blocks_64x64.N_logratio.median', 'I', "'about 39 looks' (abstract, conclusion)"),
    ('v14_lr_blocks_q1', '28.5', 'docs/enl_logratio.json',
     'pass_20200808.blocks_64x64.N_logratio.iqr[0]', 'V', None),
    ('v14_lr_blocks_q3', '46.0', 'docs/enl_logratio.json',
     'pass_20200808.blocks_64x64.N_logratio.iqr[1]', 'V', None),
    ('v14_lr_sel', '41.8', 'docs/enl_logratio.json',
     'pass_20200808.selected.local_N.median', 'V', None),
    ('v14_lr_sel_q1', '23.0', 'docs/enl_logratio.json',
     'pass_20200808.selected.local_N.iqr[0]', 'V', None),
    ('v14_lr_sel_q3', '55.0', 'docs/enl_logratio.json',
     'pass_20200808.selected.local_N.iqr[1]', 'V', None),
    ('v14_lr_709', '709', 'docs/enl_logratio.json',
     'pass_20200808.selected.n_local_N_ge_79p6', 'V', None),
    ('v14_lr_709_pct', '2.7', 'docs/enl_logratio.json',
     'pass_20200808.selected.fraction_local_N_ge_79p6', 'V', None),
    ('v14_lr_bias_lo', '3.4', 'docs/enl_logratio.json',
     'validation.rows[*].relative_bias_median|min', 'V', None),
    ('v14_lr_bias_hi', '5.0', 'docs/enl_logratio.json',
     'validation.rows[*].relative_bias_median|max', 'V', None),
    ('v14_lr_cov_lo', '66', 'docs/enl_logratio.json',
     'validation.rows[*].boot95_coverage|min', 'V', None),
    ('v14_lr_cov_hi', '72', 'docs/enl_logratio.json',
     'validation.rows[*].boot95_coverage|max', 'V', None),
    ('v14_tc_ci1_lo', '0.29', 'docs/tail_calibration_ci.json',
     'results.20200808_64px.levels.1pct.pooled_ci95[0]', 'V', None),
    ('v14_tc_ci1_hi', '0.64', 'docs/tail_calibration_ci.json',
     'results.20200808_64px.levels.1pct.pooled_ci95[1]', 'V', None),
    ('v14_tc_ci5_lo', '1.92', 'docs/tail_calibration_ci.json',
     'results.20200808_64px.levels.5pct.pooled_ci95[0]', 'V', None),
    ('v14_tc_ci5_hi', '2.75', 'docs/tail_calibration_ci.json',
     'results.20200808_64px.levels.5pct.pooled_ci95[1]', 'V', None),
    ('v14_tc_ci10_lo', '4.90', 'docs/tail_calibration_ci.json',
     'results.20200808_64px.levels.10pct.pooled_ci95[0]', 'V', None),
    ('v14_tc_ci10_hi', '6.08', 'docs/tail_calibration_ci.json',
     'results.20200808_64px.levels.10pct.pooled_ci95[1]', 'V', None),
    ('v14_tc_exp_lo', '47', 'docs/tail_calibration_ci.json',
     'results.20200808_64px.levels.1pct.expected_above_if_exactly_calibrated', 'V', None),
    ('v14_tc_exp_hi', '51', 'docs/tail_calibration_ci.json',
     'results.20200808_64px.levels.10pct.expected_above_if_exactly_calibrated', 'V', None),
    ('v14_tc32_blocks1', '501', 'docs/tail_calibration_ci.json',
     'results.20200808_32px.blocks', 'V', None),
    ('v14_tc32_blocks2', '53', 'docs/tail_calibration_ci.json',
     'results.20200305_32px.blocks', 'V', None),
    ('v14_tc32_p5_1', '4.08', 'docs/tail_calibration_ci.json',
     'results.20200808_32px.levels.5pct.pooled', 'V', None),
    ('v14_tc32_p5_2', '4.08', 'docs/tail_calibration_ci.json',
     'results.20200305_32px.levels.5pct.pooled', 'V', None),
    ('v14_tc32_above1_1', '144', 'docs/tail_calibration_ci.json',
     'results.20200808_32px.levels.1pct.blocks_above_nominal', 'V', None),
    ('v14_tc32_exp1_1', '104', 'docs/tail_calibration_ci.json',
     'results.20200808_32px.levels.1pct.expected_above_if_exactly_calibrated', 'V', None),
    ('v14_tc32_above1_2', '15', 'docs/tail_calibration_ci.json',
     'results.20200305_32px.levels.1pct.blocks_above_nominal', 'V', None),
    ('v14_tc32_exp1_2', '9', 'docs/tail_calibration_ci.json',
     'results.20200305_32px.levels.1pct.expected_above_if_exactly_calibrated', 'V', 'presence check only; small integer'),
    ('v14_tc32_p1_1', '0.89', 'docs/tail_calibration_ci.json',
     'results.20200808_32px.levels.1pct.pooled', 'V', None),
    ('v14_p2_coh', '0.751', 'docs/stokes_from_slc_20200305.json',
     'results.invariant.coherence.median', 'III', None),
    ('v14_p2_cpr', '0.146', 'docs/stokes_from_slc_20200305.json',
     'results.sign.physical_median_cpr', 'III', None),
    ('v14_p2_dop', '0.045', 'docs/stokes_from_slc_20200305.json',
     'results.invariant.dop_below_threshold.fraction', 'III', None),
    ('v14_p2_cells', '896,972', 'docs/stokes_from_slc_20200305.json',
     'slc.matched_cells', 'III', None),
    ('v14_p2_joint', '24', 'docs/stokes_from_slc_20200305.json',
     'results.joint_measured.unconditional.n_both', 'III', None),
    ('v14_f2_joint1', '88.2', 'docs/f2_maximum.json',
     'complex_field_v2.joint_rule_on_null.p_at_least_1_cell', 'V', None),
    ('v14_f2_joint1_abs', '88', 'docs/f2_maximum.json',
     'complex_field_v2.joint_rule_on_null.p_at_least_1_cell', 'I', 'abstract'),
    ('v14_f2_joint1_se', '0.3', 'docs/f2_maximum.json',
     'complex_field_v2.joint_rule_on_null.p_at_least_1_se', 'V', None),
    ('v14_f2_mean', '5.5', 'docs/f2_maximum.json',
     'complex_field_v2.joint_rule_on_null.mean_cells_selected', 'V', None),
    ('v14_f2_fwe_lo', '85', 'docs/f2_maximum.json',
     'complex_field_v2.fwe_at_1p895.rate', 'V', "'85--86 % (two runs)': 85.2 (v2) and 86.3 (the first run, f2_fwe_int)"),
    ('v14_f2_pp_lo', '7.6', 'docs/f2_maximum.json',
     'complex_field_v2.per_pixel.exceedance_rate', 'V', "'7.6--7.8 %': 7.63 (v2); 7.8 is DERIVED f2_per_pixel (the first run)"),
    ('v14_f2_interior', '6.9', 'docs/f2_maximum.json',
     'complex_field_v2.per_pixel.interior_cells_rate', 'V', None),
    ('v14_f2_tpix', '2.087', 'docs/f2_maximum.json',
     'complex_field_v2.calibrated_per_pixel_threshold.threshold', 'V', None),
    ('v14_f2_tpix_fwe', '75', 'docs/f2_maximum.json',
     'complex_field_v2.calibrated_per_pixel_threshold.fwe_at_threshold', 'V', None),
    ('v14_f2_tmax', '4.12', 'docs/f2_maximum.json',
     'complex_field_v2.crater_level_threshold.threshold_for_5pct_fwe', 'V', None),
    ('v14_tex_f_4', '22.4', 'docs/detection_statistics.json',
     'derived.f_exceedance_at_textured_enl[1].p_exceed_true_cpr_0p7_percent', 'V', 'F at the unrounded moment ENL 9.337 (22.41); replaces tex_f_4'),
    # =================================================================
    # v17a (pre-submission pass, 2026-09-24)
    # =================================================================
    ('v17_band_edge_3dp', '1.299', 'docs/stokes_from_slc.json',
     'results.invariant.t3f_coupling_band.band[1]', 'I', None),
    ('v17_n_edge', '79.6', 'docs/enl_logratio.json',
     'n_edge', 'I', 'N at which crit95 F(2N,2N) = 1.2989'),
    ('v17_ddop_139', '0.139', 'docs/propagation_percentiles.json',
     'dop.over_amplitude_mask.max', 'III', 'the III-D DOP_a excursion 1.393e-1, now also printed to three decimals'),
    ('v17_np14', '9.7', 'docs/np_power_bound.json',
     'curve[?N=14].bound_percent', 'V', None),
    ('v17_np39', '14.2', 'docs/np_power_bound.json',
     'curve[?N=39.4].bound_percent', 'V', None),
    ('v17_np39_abs', '14', 'docs/np_power_bound.json',
     'curve[?N=39.4].bound_percent', 'I', "'about 14 %' (abstract, conclusion)"),
    ('v17_np80', '20.2', 'docs/np_power_bound.json',
     'curve[?N=80].bound_percent', 'V', None),
    ('v17_np218', '37.6', 'docs/np_power_bound.json',
     'curve[?N=218].bound_percent', 'V', None),
    ('v17_np_alts', '838', 'docs/np_power_bound.json',
     'grids.numeric.alternatives', 'V', None),
    ('v17_np_cpr_step', '0.01', 'docs/np_power_bound.json',
     'grids.numeric.alternative_cpr_step', 'V', None),
    ('v17_np_dop_step', '0.005', 'docs/np_power_bound.json',
     'grids.numeric.alternative_dop_step', 'V', None),
    ('v17_np_null_cpr', '3.1e-4', 'docs/np_power_bound.json',
     'grids.numeric.null_final_spacing_cpr', 'V', 'null boundary searched to 3.1e-4 in CPR'),
    ('v17_bound_cross_lo', '30', 'docs/joint_power_curve.json',
     'summary.A.strict_band_max_first_exceeds_np_bound.between_N[0]', 'V', 'Fig. 3 caption: the rule first exceeds the bound between N = 30 and 38'),
    ('v17_bound_cross_hi', '38', 'docs/joint_power_curve.json',
     'summary.A.strict_band_max_first_exceeds_np_bound.between_N[1]', 'V', None),
    ('v17_area', '99.6', 'docs/complex_grid_correlation.json',
     'correlation_area.median_px', 'V', None),
    ('v17_w10', '10', 'docs/complex_grid_correlation.json',
     'window_31x31.W_used', 'V', 'presence check only; small integer'),
    ('v17_w10_lo', '6.8', 'docs/decision_rule.json',
     'summary.A_N14.plugin_Wcomplex.cpr_test_size_percent', 'V', None),
    ('v17_w10_hi', '7.1', 'docs/decision_rule.json',
     'summary.A_N100.plugin_Wcomplex.cpr_test_size_percent', 'V', None),
    ('v17_w10_iut', '0.07', 'docs/decision_rule.json',
     'summary.A_N100.plugin_Wcomplex.iut_size_percent', 'V', None),
    ('v17_nhat_max1', '137', 'docs/decision_rule.json',
     'product.20200808.local_N_hat.max', 'V', None),
    ('v17_nhat_max2', '229', 'docs/decision_rule.json',
     'product.20200305.local_N_hat.max', 'V', None),
    ('v17_nhat_218', '3', 'docs/decision_rule.json',
     'product.20200305.local_N_hat_counts.n_ge_218', 'V', 'presence check only; small integer'),
    ('v17_ceiling', '69.7', 'docs/complex_cell_ceiling.json',
     'ceiling_105x5.LH.median', 'V', None),
    ('v17_ceiling_abs', '70', 'docs/complex_cell_ceiling.json',
     'ceiling_105x5.LH.median', 'V', "'about 70 looks'"),
    ('v17_ceiling_lo', '67.3', 'docs/complex_cell_ceiling.json',
     'ceiling_105x5.LH.range[0]', 'V', None),
    ('v17_ceiling_hi', '86.1', 'docs/complex_cell_ceiling.json',
     'ceiling_105x5.LH.range[1]', 'V', None),
    ('v17_random', '17.5', 'docs/enl_logratio.json',
     'random_like_for_like.20200808.local_N.median', 'V', "random cells 'estimated the same way' (selected and random cells dropped from every window)"),
    ('v17_null_99', '99', 'docs/f2_maximum.json',
     'complex_field_v3_summary.null_rule_ge1_percent_both_counts.max', 'I', "'88--99 %' of null simulations"),
    ('v17_cpr07_lo', '66', 'docs/f2_maximum.json',
     'complex_field_v3_summary.cpr0p7_rule_ge1_percent.min', 'I', 'CPR 0.7 at DOP 0.176 and 0.20, both look counts'),
    ('v17_cpr07_hi', '73', 'docs/f2_maximum.json',
     'complex_field_v3_summary.cpr0p7_rule_ge1_percent.max', 'I', None),
    ('v17_cpr09_lo', '74', 'docs/f2_maximum.json',
     'complex_field_v3_summary.cpr0p9_rule_ge1_percent.min', 'V', None),
    ('v17_cpr09_hi', '97', 'docs/f2_maximum.json',
     'complex_field_v3_summary.cpr0p9_rule_ge1_percent.max', 'V', None),
    ('v17_lift', '6', 'docs/f2_maximum.json',
     'complex_field_v3_summary.complex_lags_lift_points.max', 'V', "'by up to 6 points' (5.94)"),
    ('v17_f2_ge1_lo', '87.9', 'docs/f2_maximum.json',
     'complex_field_v3_summary.null_N13p72_rule_ge1_percent', 'V', None),
    ('v17_f2_ge1_hi', '88.2', 'docs/f2_maximum.json',
     'complex_field_v3_summary.v2_rule_ge1_percent', 'V', None),
    ('v17_f2_ge5', '49', 'docs/f2_maximum.json',
     'complex_field_v3_summary.null_N13p72_rule_ge5_percent', 'V', '48.86 (v3) and 49.31 (v2) both print 49'),
    ('v17_enl_16', '16', 'docs/f2_maximum.json',
     'complex_field_v3_summary.delivered_N13p72_achieved_enl', 'V', "'14.5--16': 14.50 (first run), 15.98 (v3)"),
    ('v17_looks11', '11', 'docs/f2_maximum.json',
     'complex_field_v3_summary.delivered_N39_looks', 'V', 'presence check only; small integer'),
    ('v17_enl405', '40.5', 'docs/f2_maximum.json',
     'complex_field_v3_summary.delivered_N39_achieved_enl', 'V', None),
    ('v17_n39_ge1', '99.1', 'docs/f2_maximum.json',
     'complex_field_v3_summary.null_N39_rule_ge1_percent', 'V', None),
    ('v17_n39_ge5', '94.2', 'docs/f2_maximum.json',
     'complex_field_v3_summary.null_N39_rule_ge5_percent', 'V', None),
    ('v17_n39_crit', '1.444', 'docs/f2_maximum.json',
     'complex_field_v3_summary.null_N39_crit_at_achieved', 'V', None),
    ('v17_n39_cpr', '88.1', 'docs/f2_maximum.json',
     'complex_field_v3_summary.null_N39_cpr_only_ge1_percent', 'V', None),
    ('v17_n39_1895', '31', 'docs/f2_maximum.json',
     'complex_field_v3_summary.null_N39_cpr_only_at_1p895_percent', 'V', None),
]

#: Arithmetic checked here, with the inputs audited on their own rows.
DERIVED = [
    ("x_bound", 0.2614797, lambda: 2 * math.atanh(0.13), 1e-6),
    ("factor", 235.0, lambda: 1.0 / 0.004261057358235121, 1.0),
    ("t2_n1372_bias", 1.079, lambda: 13.72 / (13.72 - 1.0), 1e-3),
    ("floor38", 1.44, lambda: ((2 * 38 - 1) / (38 - 2)) ** 0.5, 5e-3),
    ("floor6", 1.66, lambda: ((2 * 6 - 1) / (6 - 2)) ** 0.5, 5e-3),
    ("crossing_rel", 5.99e-6,
     lambda: abs(0.004261057358235121 - 0.004261082862785302)
             / 0.004261082862785302, 5e-8),
    # "one cell in 66" was deleted from III-E as redundant with the 1.50 %;
    # the reciprocal is still in the artifact
    # (stokes_from_slc.json::...dop_below_threshold.one_cell_in = 66.54).
    # "a calibration field alone can move a pixel's DOP by 1.07x the width of
    # the 0.13 criterion"
    ("dop_ratio", 1.07, lambda: 0.1392841339111328 / 0.13, 5e-3),
    # the tail is narrower than F by 14 % and 19 % at those percentiles.
    # 19, not 20: 100 * (1 - 0.80520) = 19.48. The manuscript now states the
    # two percentiles separately instead of rounding them into a range.
    ("tail_gap_lo", 14.0, lambda: 100 * (1 - 0.859035173822312), 0.5),
    ("tail_gap_hi", 19.0, lambda: 100 * (1 - 0.8052039479277788), 0.5),
    # the ratio bias at the two look counts
    ("bias_n5_pct", 25.0, lambda: 100 * (5 / 4 - 1), 0.05),
    ("bias_n1372_pct", 7.9, lambda: 100 * (13.72 / 12.72 - 1), 0.05),
    # 21 x 51.016 reproduces the declared total processed bandwidth
    ("look_bw_product", 1071.336, lambda: 21 * 51.016, 5e-3),
    # the simulated coherence is the square root of the measured intensity
    # correlation under the circular-Gaussian relation
    ("rho_from_corr", 0.9822, lambda: 0.9647125999763775 ** 0.5, 5e-4),
    # III-E: a pixel at the F2 peak of 1.95 has DOP >= |1-1.95|/(1+1.95)
    ("f2_dop_min", 0.32, lambda: (1.95 - 1) / (1.95 + 1), 5e-3),
    # III-E: 0.658 gives 0.21, (1 - 0.658)/(1 + 0.658)
    ("coh_to_cpr", 0.21, lambda: (1 - 0.658042) / (1 + 0.658042), 5e-3),
    # V-B: 1521 / 61.42
    ("f2_eff_arith", 24.8, lambda: 1521 / 61.42, 0.05),
    # V-C: the analytic F(28, 28) exceedance at a true CPR of 0.7
    ("f28_07", 17.5, lambda: 17.544925186078576, 0.05),
    # V-C: gamma_c^2 ~ 0.02 under Gaussian speckle, from the 0.13 median outside the gate
    ("gamma_c_sq", 0.02, lambda: _j("docs/stokes_from_slc.json")["results"]["coherence_by_gate"]
     ["outside_gate"]["gamma_c"]["median"] ** 2, 0.005),
    # V-B: 7.8 % per pixel = the first complex run's mean area above 1.895 / 260
    ("f2_per_pixel", 7.8, lambda: 100 * _j("docs/f2_maximum.json")["complex_field"]["true_cpr_1"]
     ["area_gt_crit"]["mean"] / 260, 0.05),
    # ---- v14 (final pass) ---------------------------------------------
    # V-A: the one-sided 95 % critical value of F(2N, 2N) and P(R > 1) at a
    # true CPR of 0.7, at the log-ratio look count 39.4
    ("v14_crit394", 1.452, lambda: __import__("scipy.stats", fromlist=["f"]).f.ppf(0.95, 78.8, 78.8), 5e-4),
    ("v14_p07_394", 5.8, lambda: 100 * __import__("scipy.stats", fromlist=["f"]).f.sf(1 / 0.7, 78.8, 78.8), 0.05),
    # V-B: the smallest DOP a population at CPR 0.9 admits, Eq. (6)
    ("v14_dopmin09", 0.053, lambda: (1 - 0.9) / (1 + 0.9), 5e-4),
    # V-B: the look count at which crit95(F(2N, 2N)) = 1.2989
    ("v14_n_edge", 79.6, lambda: __import__("scipy.optimize", fromlist=["brentq"]).brentq(
        lambda n: __import__("scipy.stats", fromlist=["f"]).f.ppf(0.95, 2 * n, 2 * n) - 1.13 / 0.87,
        20, 400), 0.05),

    # ---- v17a ---------------------------------------------------------------
    # II-A: G as power factors would shift the channel ratio by 0.08 dB
    ("v17_gain_db", 0.08, lambda: 10 * math.log10(1.018442 / 1.000923), 0.005),
    # III-E: the phase cluster's offset from quadrature, from its circular mean
    ("v17_quad_offset", 1.7, lambda: 90.0 - abs(_j("docs/stokes_from_slc.json")["results"]["sign"]
                                                 ["phase_evidence"]["circular_mean_deg"]), 0.05),
]

#: "about X": compared at a stated RELATIVE tolerance, because the manuscript
#: says it is approximate. (id, printed, artifact, key, rel_tol, section, note)
APPROX = [
    ("win_pred_cpr", "0.7", "docs/stokes_from_slc.json",
     "results.t3e.180_deg.coherence_predicts_cpr.predicted_median", 0.05, "III",
     "'(about 0.7, more depolarized terrain)'; predicted 0.704"),
    ("win_obs_cpr", "0.7", "docs/stokes_from_slc.json",
     "results.t3e.180_deg.coherence_predicts_cpr.observed_median", 0.05, "III",
     "observed 0.718"),
]

#: Identifiers printed verbatim. The artifact string must START WITH the
#: printed one (the manuscript drops the label's _xx_d18.xml suffix).
#: (id, printed, artifact, key, section, note)
STRINGS = [
    ("gen_product", "ch2_sar_ncxl_20200305t114902885_d_sri_xx_cp",
     "docs/enl_L_20200305.json", "label.source", "IV", "second acquisition"),
    ("main_product", "ch2_sar_ncxl_20200808t201154198_d_sri_xx_cp",
     "docs/dop_exclusion.json", "calibration.product", "II",
     "contained in the artifact's product field"),
    ("v17_eff_count", "binomial, at each", "docs/tail_calibration_ci.json", "reference_distribution", "V",
     "'(binomial, at each block's effective sample count)': the exact-calibration reference"),
]

#: QUANTIFIED CLAIMS -- "all", "every", "each", "identical", "in every one of".
#: The audit once passed "1071.2 Hz in all nine windows" and "3.10, identical
#: in all nine windows" because it compared the printed number with a MEDIAN
#: key: a claim about every element was checked against one summary of them.
#: Each row here tests the claim against EVERY element of the array behind it.
#:
#: (id, anchor, checks, section, note)
#:   anchor  -- regex that must match within 120 characters of the quantifier
#:              in the manuscript; it ties the row to the sentence. A LaTeX
#:              backslash is written \\ (in a raw string): \ref would be read
#:              as a carriage return and \, as a bare comma
#:   checks  -- list of (artifact, key-with-[*]-or-filter, test)
#:   test    -- ("rounds_to", "3.10")      every element rounds to it
#:              ("within", lo, hi)         every element in [lo, hi]
#:              ("below", x) / ("above", x) every element strictly below/above
#:              ("equals", v)              every element == v
#:              ("count", n)               the array has n elements
#:              ("all_are", "no")          every element is that string
#:              ("none_are", "yes")        no element is that string
#:              ("yes_only_for_id", 2)     "yes" appears, and only on record 2
QUANTIFIED = [
    ("q_eq1_every_cell", r"interval\}\) at every cell",
     [("docs/stokes_from_slc.json", "results.t3b_180.violation_fraction", ("equals", 0.0)),
      ("docs/stokes_from_slc.json", "results.t3b_0.violation_fraction", ("equals", 0.0))],
     "III", "fraction of cells outside Eq. (1)'s band, both signs"),
    ("q_band_every_cell", r"at every cell with",
     [("docs/stokes_from_slc.json", "results.invariant.t3f_coupling_band.fraction_outside",
       ("equals", 0.0))],
     "III", "every DOP < 0.13 cell inside the coupling band"),
    ("q_selected_below_130", r"every one with a measured CPR below 1\.30",
     [("docs/stokes_from_slc.json", "results.invariant.t3f_coupling_band.fraction_outside",
       ("equals", 0.0)),
      ("docs/stokes_from_slc.json", "results.invariant.t3f_coupling_band.band[1]",
       ("below", 1.30))],
     "III", "no low-DOP cell outside (0.7699, 1.2989), and 1.2989 < 1.30"),
    ("q_bias_every_N", r"at every look count tes",
     [("docs/enl_benchmark.json", "synthetic.rows[?texture_label=inf].relative_bias",
       ("within", 0.14, 0.18))],
     "IV", "'about 16 % high at every look count tested': speckle-only rows, "
           "N = 4, 6, 8, 12, each within 14-18 %"),
    ("q_oversampling_nine", r"in every one of the nine windows",
     [("docs/slc_multilook_control.json", "windows[*].oversampling_factor",
       ("rounds_to", "3.10")),
      ("docs/slc_multilook_control.json", "windows[*].oversampling_factor", ("count", 9))],
     "IV", "the claim the median key once passed; now per window"),
    ("q_all_pixels_fig1", r"over all \$2\\,337\\,086\$",
     [("docs/dop_exclusion.json", "measured_pixels", ("equals", 2337086.0)),
      ("docs/dop_exclusion.json", "figure_cache_cross_check.n", ("equals", 2337086.0))],
     "III", "Fig. 1 is drawn over every measured pixel"),
    ("q_all_pixels_resid", r"across all\s+\$2\\,337\\,086\$",
     [("frontend/public/analysis/faustini.json", "cpr_dop_identity.verified_over_pixels",
       ("equals", 2337086.0))],
     "III", "the residual is taken over every measured pixel"),
    # "none reports X" is a universal claim about the 25 screened records. It
    # holds if NO record says yes; an abstract-only record's "not found in the
    # accessible material" is the weaker sense VIII-C states for those eleven.
    # ---- v11 --------------------------------------------------------------
    ("q_v11_abstract_selected", r"every cell the joint criterion selects",
     [("docs/stokes_from_slc.json", "results.invariant.t3f_coupling_band.fraction_outside",
       ("equals", 0.0)),
      ("docs/stokes_from_slc.json", "results.invariant.t3f_coupling_band.band[1]", ("below", 1.299))],
     "I", "every selected cell has measured CPR < 1.2989"),
    ("q_v11_intro_none", r"none reports a critical value or the rate",
     [("docs/literature_screen.json", "records[?relevant_lunar_cpr_ice_study=true].critical_value_reported",
       ("none_are", "yes")),
      ("docs/literature_screen.json", "records[?relevant_lunar_cpr_ice_study=true].exceedance_rate_reported",
       ("none_are", "yes"))], "I", None),
    ("q_v11_iv_none", r"None reports a per-pixel critical",
     [("docs/literature_screen.json", "records[?relevant_lunar_cpr_ice_study=true].critical_value_reported",
       ("none_are", "yes")),
      ("docs/literature_screen.json", "records[?relevant_lunar_cpr_ice_study=true].exceedance_rate_reported",
       ("none_are", "yes"))], "VIII", None),
    ("q_v11_texture_zero", r"every procedure covers\s+0",
     [("docs/enl_interval_validation.json", f"rows[?texture=order 8].coverage.{p}.95.coverage",
       ("equals", 0.0)) for p in ("block2d_percentile", "block2d_basic", "parametric_neyman",
                                  "parametric_basic")], "IV", None),
    ("q_v11_each_window", r"the measured spectrum of each\s+window",
     [("docs/mechanism_spec.json", "per_window[*].participation_ratio", ("within", 6.875, 7.205))],
     "IV", "'7.13 (6.88--7.20)'"),
    ("q_v11_four_looks", r"four looks\s+each",
     [("docs/f2_maximum.json", "complex_field.looks", ("equals", 4.0))], "V", None),
    ("q_v11_all_109_p99", r"to the 99th in all 109",
     [("docs/stokes_from_slc.json",
       "results.t3e.180_deg.two_channel_models.blocks_64x64.p99.closest_model_counts.unequal",
       ("equals", 109.0))], "V", None),
    ("q_v11_all_109_equal", r"at or below the\s+equal-look model",
     [("docs/stokes_from_slc.json", "results.t3e.180_deg.blocks_64x64[*].models.ordering_p95",
       ("none_are", "empirical > equal_low_N"))], "V", "every block's p95 at or below equal-look F"),
    # ---- v14 (final pass) ---------------------------------------------
    ("q_v14_second_pass_every_cell", r"hold at every\s+cell",
     [("docs/stokes_from_slc_20200305.json", "results.t3b_180.violation_fraction", ("equals", 0.0)),
      ("docs/stokes_from_slc_20200305.json", "results.invariant.t3f_coupling_band.fraction_outside",
       ("equals", 0.0)),
      ("docs/stokes_from_slc_20200305.json", "results.coherence_by_gate.identity.max_abs_residual",
       ("below", 1e-15))],
     "III", "second pass: the interval, the band and the coherence identity at every cell"),
    ("q_v14_fig2_all_cells", r"All \$5\\,883\\,594\$\s+cells",
     [("docs/stokes_from_slc.json", "slc.matched_cells", ("equals", 5883594.0))],
     "III", "Fig. 2 is drawn over every matched cell (fig_cpr_dop_density.npz, n = 5 883 594)"),
    ("q_v14_fig2_every_cell", r"Every cell lies on or inside",
     [("docs/stokes_from_slc.json", "results.t3b_180.violation_fraction", ("equals", 0.0)),
      ("docs/stokes_from_slc.json", "results.invariant.t3f_coupling_band.fraction_outside", ("equals", 0.0))],
     "III", "no cell outside Eq. (1)'s band; no DOP < 0.13 cell outside the coupling band"),
    ("q_v14_iut_no_cell", r"it selects no cell on either pass",
     [("docs/decision_rule.json", "product.20200808.iut_selects", ("equals", 0.0)),
      ("docs/decision_rule.json", "product.20200305.iut_selects", ("equals", 0.0))],
     "V", None),
    ("q_v14_identity_every_cell", r"identity that holds on every\s+cell",
     [("docs/stokes_from_slc.json", "results.coherence_by_gate.identity.max_abs_residual",
       ("below", 1e-15)),
      ("docs/stokes_from_slc.json", "results.coherence_by_gate.gamma_c_ge_threshold_inside_gate",
       ("equals", 0.0))], "V", None),
    ("q_v14_each_block", r"two channels in each block",
     [("docs/stokes_from_slc.json", "results.t3e.180_deg.blocks_64x64[*].models.gamma_c_pooled",
       ("count", 109))], "V", "the moment ENLs are per block, all 109"),
    ("q_v14_concl_selected", r"every cell the joint criterion\s+selects has a measured CPR below 1\.299",
     [("docs/stokes_from_slc.json", "results.invariant.t3f_coupling_band.fraction_outside",
       ("equals", 0.0)),
      ("docs/stokes_from_slc.json", "results.invariant.t3f_coupling_band.band[1]", ("below", 1.299))],
     "IX", None),

    # ---- v17a ---------------------------------------------------------------
    ("q_v17_proxy_all", r"all give a proxy median of 0\.00043",
     [("docs/cpr_significance.json", "monte_carlo[0:4].amplitude_proxy.median", ("rounds_to", "0.00043"))],
     "III", "the four equal-power rows, CPR 0.30 / 0.70 / 1.00 / 1.50"),
    ("q_v17_never_same", r"never the same one",
     [("docs/decision_rule.json", "product.20200808.both_tests_reject", ("equals", 0.0))], "V", None),
    ("q_v17_none_254", r"none 254 and none among",
     [("docs/decision_rule.json", "product.20200808.local_N_hat_counts.n_ge_254", ("equals", 0.0)),
      ("docs/decision_rule.json", "product.20200305.local_N_hat_counts.n_ge_254", ("equals", 0.0)),
      ("docs/decision_rule.json", "product.20200808.published_rule_cells.local_N_hat_counts.n_ge_218", ("equals", 0.0)),
      ("docs/decision_rule.json", "product.20200305.published_rule_cells.local_N_hat_counts.n_ge_218", ("equals", 0.0))],
     "V", "no cell reaches 254 on either pass; no published-rule cell reaches 218"),
    ("q_v17_each_838", r"for each of 838 populations",
     [("docs/np_power_bound.json", "grids.numeric.alternatives", ("equals", 838.0)),
      ("docs/np_power_bound.json", "curve[*].bound_percent", ("above", 4.999))], "V", None),
    ("q_v17_lift", r"raise each joint-rule rate by up to 6 points",
     [("docs/f2_maximum.json", "complex_field_v3_summary.complex_lags_lift_points.max", ("below", 6.0)),
      ("docs/f2_maximum.json", "complex_field_v3_summary.complex_lags_lift_points.min", ("above", 0.0))],
     "V", "every population and look count: the complex lags raise the rate, by 0.11 to 5.94 points"),
    ("q_v17_within_04", r"within 0\.4 points of its size",
     [("docs/joint_power_curve.json", "summary.A.strict_band_max_abs_diff_to_size_below_first_5pct.points",
       ("below", 0.4))], "V", "largest |strict band - size| over N < 19 is 0.346 (N = 17)"),

]

#: Quantified rows retired by v11, with the reason.
RETIRED_QUANTIFIED_V11 = {
    "q_half_realizations": "'about half of all realizations' (v11 prints the rates)",
    "q_table_every_N": "the scope row now reads 'for N<80'",
    "q_bias_every_study": "(iii) reworded: 'no other record examined reports' (q_v11_iii_bias)",
    "q_criterion_every_study": "the 'every study except [sinha2026]' sentence is gone",
    "q_lit_intro_none": "reworded (q_v11_intro_none)",
    "q_lit_iv_none": "reworded (q_v11_iv_none)",
}

#: Quantifier sentences that are not claims about an array: algebraic
#: identities, definitions of method, scope statements, conditionals. Each is
#: listed with the reason, so a NEW quantified sentence is flagged until
#: somebody decides which kind it is. (anchor, reason)
QUANTIFIER_EXEMPT = [
    (r"every absence claim is scoped", "editorial: the contributions list"),
    (r"Every statistic on the delivered product", "method: which mask a statistic uses"),
    (r"Each is stored as an unsigned 16-bit", "label field (UnsignedLSB2), not a number claim"),
    (r"contains unity for every\s+pixel", "algebraic: c <= 1 <= 1/c for every amplitude pair"),
    (r"identically, \$\\mathrm\{CPR\}_a>1\$ is empty", "algebraic: CPR_a = c <= 1"),
    (r"every pixel the screen rejects", "algebraic: the complement argument"),
    (r"Each\s+pixel is bound individually", "algebraic: Eq. (6) per Stokes vector"),
    (r"every downstream statistic is a frame-wide summary", "editorial scope"),
    (r"identical estimator", "method: the same estimator on both arms"),
    (r"identical pipeline", "method: the benchmark uses the production pipeline"),
    (r"moments of each intensity", "model statement about an ENL"),
    (r"would each explain", "conditional: either explanation suffices"),
    (r"would each have failed it", "conditional: falsification criteria"),
    (r"zero algebraically for every\s+admissible input", "algebraic; G31 checks it on corrupted inputs"),
    (r"all languages and document types", "search protocol, literature_search.json"),
    (r"Every result from", "scope: conditional on the amplitude reading"),
    (r"in all sections", "disclosure statement"),
    (r"none of\s+three candidate causes", "judgement over enl_L_20200305_full.json::candidate_causes; "
     "no per-cause numeric field"),
    (r"none an ISRO statement", "editorial: the provenance of the three facts"),
    (r"every power of a low-variance variable", "mathematical: moment ENL of x^k"),
    (r"none recovers the per-pixel sign", "algebraic: the sign of S3 is not in the powers"),
    (r"moments are each invertible", "mathematical: F(2N,2N) moments are monotone in N"),
    (r"0\.45\\,\\% of all cells", "'of all cells' is the denominator of a measured fraction"),
    (r"every\s+selected cell holding a measured CPR below the\s+critical value",
     "restates q_selected_below_130 in the conclusion; checked there"),
    # ---- v14 ---------------------------------------------------------------
    (r"at every \$N\$ below 79\.6", "mathematical: crit95 of F(2N,2N) decreases in N and equals "
     "1.2989 at N = 79.6166 (DERIVED v14_n_edge)"),
    (r"each selected\s+cell's", "method: which window N is estimated from"),
    (r"every cell is formed by the same averaging", "method: one averaging kernel for every cell"),
    (r"estimated from each cell's", "method: which window N is estimated from (the count is q_v14_iut_no_cell)"),
    (r"zero for every admissible input", "algebraic; G31 checks it on corrupted inputs"),
    # ---- v17a ---------------------------------------------------------------
    (r"contains unity at every pixel", "algebraic: c <= 1 <= 1/c for every amplitude pair (the contributions list)"),
    (r"screen selects\s+none of the", "algebraic: CPR_a <= 4.261e-3 wherever DOP_a < 0.13 (Eq. 6); G31 checks it on corrupted inputs"),
    (r"recovers each CPR", "the four Stokes medians, no longer printed, are 0.300 / 0.700 / 1.000 / 1.500 "
     "(cpr_significance.json::monte_carlo[0:4].stokes_cpr.median), each within 0.1 % of its true CPR"),
    (r"Every cell is formed by the same averaging", "method: one averaging kernel for every cell"),
    (r"at each CPR's minimum DOP", "method: which populations the strict band summary uses"),
    (r"bounds that of every level-5", "mathematical: the Neyman-Pearson lemma applied to each simple null"),
    (r"at each\s+block's effective sample count", "method: the exact-calibration reference (v17_eff_count)"),
]

#: The Supplementary Material (v17a): S-I (Mini-RF moments) and S-II (the
#: literature search), audited when --tex names the supplement. Rows copied
#: from AUDIT where the figure is also in the main text, moved where it is not
#: (RETIRED_V17A says which), and every remaining Table S1 cell keyed.
SUPPLEMENT_AUDIT = [
    ('g2_hermite', '6.12', 'docs/published_moments.json',
     'craters[0].excess_kurtosis', 'VI', 'transcribed from Fa & Cai Table 1'),
    ('g2_rozh', '7.66', 'docs/published_moments.json',
     'craters[1].excess_kurtosis', 'VI', None),
    ('g2_main', '7.06', 'docs/published_moments.json',
     'craters[2].excess_kurtosis', 'VI', None),
    ('g2_schom', '6.51', 'docs/published_moments.json',
     'craters[3].excess_kurtosis', 'VI', None),
    ('g2_card', '7.19', 'docs/published_moments.json',
     'craters[4].excess_kurtosis', 'VI', None),
    ('g2_byrg', '7.33', 'docs/published_moments.json',
     'craters[5].excess_kurtosis', 'VI', None),
    ('g2_doll', '7.00', 'docs/published_moments.json',
     'craters[6].excess_kurtosis', 'VI', None),
    ('g2_stev', '7.95', 'docs/published_moments.json',
     'craters[7].excess_kurtosis', 'VI', None),
    ('n_hermite_sd', '9.11', 'docs/published_moments.json',
     'craters[0].N_from_dispersion', 'VI', None),
    ('n_hermite_g1', '9.65', 'docs/published_moments.json',
     'craters[0].N_from_skewness', 'VI', None),
    ('n_hermite_g2', '9.94', 'docs/published_moments.json',
     'craters[0].N_from_kurtosis', 'VI', None),
    ('n_card_g1', '7.49', 'docs/published_moments.json',
     'craters[4].N_from_skewness', 'VI', 'the widest per-crater spread'),
    ('n_card_g2', '9.12', 'docs/published_moments.json',
     'craters[4].N_from_kurtosis', 'VI', None),
    ('pm_spread', '3.8', 'docs/published_moments.json',
     'agreement_sd_vs_skew_percent_from_printed_medians', 'VI', 'from the printed medians; from the unrounded ones it is 3.7'),
    ('lit_unique', '34', 'docs/literature_search.json',
     'counts.unique', 'VIII', 'presence check only; small integer'),
    ('minirf_zoom_cdr', '14.8', 'docs/published_moments.json',
     'mode_table.zoom.cdr_pixel_spacing_m', 'VI', 'the product Fa & Cai analysed'),
    ('lit_excluded', '9', 'docs/literature_search.json',
     'counts.excluded', 'VIII', 'presence check only; small integer'),
    ('lit_fulltext', '14', 'docs/literature_screen.json',
     'counts.access.full_text', 'VIII', 'after the 2026-09-16 re-screen'),
    ('lit_abstract', '11', 'docs/literature_screen.json',
     'counts.access.abstract_only', 'VIII', None),
    ('pm_med_sigma', '8.75', 'docs/published_moments.json',
     'median_N_from_dispersion', 'VI', None),
    ('pm_med_skew', '9.08', 'docs/published_moments.json',
     'median_N_from_skewness', 'VI', None),
    ('pm_med_kurt', '9.17', 'docs/published_moments.json',
     'median_N_from_kurtosis', 'VI', None),
    ('minirf_zoom_looks', '8', 'docs/published_moments.json',
     'mode_table.zoom.nominal_looks', 'VI', 'presence check only; small integer'),
    ('minirf_effective', '6.7', 'docs/published_moments.json',
     'mode_table.effective_looks_reported.value', 'VI', 'Spudis et al. 2013, attributed to unpublished analysis'),
    ('lit_relevant', '25', 'docs/literature_search.json',
     'counts.relevant', 'VIII', 'presence check only; small integer'),
    ('s1_0_mu', '0.97', 'docs/published_moments.json',
     'craters[0].mu', 'S-I', 'Hermite B'),
    ('s1_0_sd', '0.50', 'docs/published_moments.json',
     'craters[0].sigma', 'S-I', 'Hermite B'),
    ('s1_0_g1', '1.75', 'docs/published_moments.json',
     'craters[0].skewness', 'S-I', 'Hermite B'),
    ('s1_1_mu', '0.93', 'docs/published_moments.json',
     'craters[1].mu', 'S-I', 'Rozhdestvenskiy N'),
    ('s1_1_sd', '0.50', 'docs/published_moments.json',
     'craters[1].sigma', 'S-I', 'Rozhdestvenskiy N'),
    ('s1_1_g1', '1.83', 'docs/published_moments.json',
     'craters[1].skewness', 'S-I', 'Rozhdestvenskiy N'),
    ('s1_1_nsd', '8.51', 'docs/published_moments.json',
     'craters[1].N_from_dispersion', 'S-I', 'Rozhdestvenskiy N'),
    ('s1_1_ng1', '9.14', 'docs/published_moments.json',
     'craters[1].N_from_skewness', 'S-I', 'Rozhdestvenskiy N'),
    ('s1_1_ng2', '8.84', 'docs/published_moments.json',
     'craters[1].N_from_kurtosis', 'S-I', 'Rozhdestvenskiy N'),
    ('s1_2_mu', '0.92', 'docs/published_moments.json',
     'craters[2].mu', 'S-I', 'Main L'),
    ('s1_2_sd', '0.48', 'docs/published_moments.json',
     'craters[2].sigma', 'S-I', 'Main L'),
    ('s1_2_g1', '1.82', 'docs/published_moments.json',
     'craters[2].skewness', 'S-I', 'Main L'),
    ('s1_2_nsd', '8.94', 'docs/published_moments.json',
     'craters[2].N_from_dispersion', 'S-I', 'Main L'),
    ('s1_2_ng1', '9.20', 'docs/published_moments.json',
     'craters[2].N_from_skewness', 'S-I', 'Main L'),
    ('s1_2_ng2', '9.21', 'docs/published_moments.json',
     'craters[2].N_from_kurtosis', 'S-I', 'Main L'),
    ('s1_3_mu', '0.99', 'docs/published_moments.json',
     'craters[3].mu', 'S-I', 'Schomberger A'),
    ('s1_3_sd', '0.50', 'docs/published_moments.json',
     'craters[3].sigma', 'S-I', 'Schomberger A'),
    ('s1_3_g1', '1.77', 'docs/published_moments.json',
     'craters[3].skewness', 'S-I', 'Schomberger A'),
    ('s1_3_nsd', '9.42', 'docs/published_moments.json',
     'craters[3].N_from_dispersion', 'S-I', 'Schomberger A'),
    ('s1_3_ng1', '9.51', 'docs/published_moments.json',
     'craters[3].N_from_skewness', 'S-I', 'Schomberger A'),
    ('s1_3_ng2', '9.61', 'docs/published_moments.json',
     'craters[3].N_from_kurtosis', 'S-I', 'Schomberger A'),
    ('s1_4_mu', '0.83', 'docs/published_moments.json',
     'craters[4].mu', 'S-I', 'Cardanus E'),
    ('s1_4_sd', '0.46', 'docs/published_moments.json',
     'craters[4].sigma', 'S-I', 'Cardanus E'),
    ('s1_4_g1', '2.19', 'docs/published_moments.json',
     'craters[4].skewness', 'S-I', 'Cardanus E'),
    ('s1_4_nsd', '8.11', 'docs/published_moments.json',
     'craters[4].N_from_dispersion', 'S-I', 'Cardanus E'),
    ('s1_5_mu', '1.12', 'docs/published_moments.json',
     'craters[5].mu', 'S-I', 'Byrgius C'),
    ('s1_5_sd', '0.59', 'docs/published_moments.json',
     'craters[5].sigma', 'S-I', 'Byrgius C'),
    ('s1_5_g1', '1.88', 'docs/published_moments.json',
     'craters[5].skewness', 'S-I', 'Byrgius C'),
    ('s1_5_nsd', '8.80', 'docs/published_moments.json',
     'craters[5].N_from_dispersion', 'S-I', 'Byrgius C'),
    ('s1_5_ng1', '8.85', 'docs/published_moments.json',
     'craters[5].N_from_skewness', 'S-I', 'Byrgius C'),
    ('s1_5_ng2', '9.03', 'docs/published_moments.json',
     'craters[5].N_from_kurtosis', 'S-I', 'Byrgius C'),
    ('s1_6_mu', '1.00', 'docs/published_moments.json',
     'craters[6].mu', 'S-I', 'Dollond E'),
    ('s1_6_sd', '0.53', 'docs/published_moments.json',
     'craters[6].sigma', 'S-I', 'Dollond E'),
    ('s1_6_g1', '1.85', 'docs/published_moments.json',
     'craters[6].skewness', 'S-I', 'Dollond E'),
    ('s1_6_nsd', '8.71', 'docs/published_moments.json',
     'craters[6].N_from_dispersion', 'S-I', 'Dollond E'),
    ('s1_6_ng1', '9.02', 'docs/published_moments.json',
     'craters[6].N_from_skewness', 'S-I', 'Dollond E'),
    ('s1_6_ng2', '9.25', 'docs/published_moments.json',
     'craters[6].N_from_kurtosis', 'S-I', 'Dollond E'),
    ('s1_7_mu', '1.04', 'docs/published_moments.json',
     'craters[7].mu', 'S-I', 'Stevinus A'),
    ('s1_7_sd', '0.56', 'docs/published_moments.json',
     'craters[7].sigma', 'S-I', 'Stevinus A'),
    ('s1_7_g1', '1.93', 'docs/published_moments.json',
     'craters[7].skewness', 'S-I', 'Stevinus A'),
    ('s1_7_nsd', '8.49', 'docs/published_moments.json',
     'craters[7].N_from_dispersion', 'S-I', 'Stevinus A'),
    ('s1_7_ng1', '8.59', 'docs/published_moments.json',
     'craters[7].N_from_skewness', 'S-I', 'Stevinus A'),
    ('s1_7_ng2', '8.67', 'docs/published_moments.json',
     'craters[7].N_from_kurtosis', 'S-I', 'Stevinus A'),
]

SUPPLEMENT_QUANTIFIED = [
    ('q_lit_one_of_25', 'none reports one for a DFSAR product',
     [('docs/literature_screen.json', 'counts.claims_yes.measured_ENL_reported', ('count', 1)), ('docs/literature_screen.json', 'records[?relevant_lunar_cpr_ice_study=true].measured_ENL_reported', ('yes_only_for_id', 2))],
     'VIII', 'exactly one record reports a measured ENL, and it is Spudis et al. (Mini-RF, id 2), not a DFSAR study'),
    ('q_lit_none_crit', 'none reports a per-pixel critical value',
     [('docs/literature_screen.json', 'records[?relevant_lunar_cpr_ice_study=true].critical_value_reported', ('none_are', 'yes')), ('docs/literature_screen.json', 'records[?relevant_lunar_cpr_ice_study=true].exceedance_rate_reported', ('none_are', 'yes'))],
     'VIII', None),
    ('q_cardanus_uniformly', 'do not\\s+agree uniformly',
     [('docs/published_moments.json', 'craters[?name=Cardanus E].N_from_skewness', ('rounds_to', '7.49')), ('docs/published_moments.json', 'craters[?name=Cardanus E].N_from_kurtosis', ('rounds_to', '9.12'))],
     'VI', "'Cardanus E spans 7.49--9.12'"),
]

SUPPLEMENT_QUANTIFIER_EXEMPT = [
    (r"all languages and document types", "search protocol, literature_search.json"),
    (r"moments are each invertible", "mathematical: F(2N,2N) moments are monotone in N"),
    (r"three inversions agree by construction", "mathematical: at zero terrain the three moment inversions coincide"),
    (r"absence claims are claims about these 25 records", "scope statement"),
    (r"of six\s+of the eight craters", "ordering count, read from Table S1 (s1_* rows)"),
]

#: Rows retired by v17a, with the reason.
RETIRED_V17A = {
    'rho': "the simulated H-V coherence 0.9822: v17a III-C says 'at the measured H--V correlation' without the figure",
    'lhlv_corr': 'the measured LH-LV correlation 0.9647: as rho',
    'mc_stokes_med_03': "the four Stokes medians: v17a III-C says the Stokes estimator 'recovers each CPR' (exempt, with the values in the reason)",
    'mc_stokes_med_07': 'as mc_stokes_med_03',
    'mc_stokes_med_10': 'as mc_stokes_med_03',
    'mc_stokes_med_15': 'as mc_stokes_med_03',
    'coh_q1': 'the coherence IQR 0.464-0.786: v17a III-E keeps the median 0.658',
    'coh_q3': 'as coh_q1',
    'patches_21489': 'the IV-B spatial-arm estimator comparison (21 489 patches; 6.09 / 4.83 / 4.64) is gone from v17a',
    'trace_moment': 'as patches_21489',
    'log_cumulant': 'as patches_21489',
    'moment_lh': 'as patches_21489',
    'bg_112': 'the 1.12-background exceedance 62 %: v17a V-A drops the sentence',
    'putrevu_cpr': 'the Putrevu external-check CPR 1.07: not printed in v17a',
    'joint_sim': 'the 1.8 % simulated joint rate at a 0.7 background: not printed in v17a',
    'size21': "the size 6.2 % at N = 21: v17a prints 'from N = 19 (21 with texture)'",
    'f2_max07': 'the 1.75 median maximum at a 0.7 background: v17a V-C reports the v3 crater-level rates instead',
    'sb_adj': 'the adjacent / distant sub-band correlations 0.19 / 0.02: gone from v17a IV-B',
    'sb_far': 'as sb_adj',
    'factor_full': "234.68: v17a prints 235x (row 'factor')",
    'v14_cpr09_min38': 'the N = 38 ice-free rates 9.9 / 1.8 %: v17a V-B drops the sentence; V-C reports crater-level rates',
    'v14_cpr07_d20_38': 'as v14_cpr09_min38',
    'v14_dr_w16_lo': "the W = 16 plug-in size 6.2-6.5 %: v17a prints the complex-grid window's 6.8-7.1 % (v17_w10_lo / hi)",
    'v14_dr_w16_hi': 'as v14_dr_w16_lo',
    'v14_dr_iut100': "0.015 %: v17a prints the complex-grid window's 0.07 % (v17_w10_iut)",
    'v14_prod_cpr1_frac': '0.063 %: not printed in v17a (3703 cells is)',
    'v14_prod_dop2': '593: not printed in v17a',
    'v14_tc32_p10_1': 'the 32 x 32 rates at 10 % and 1 %: v17a keeps 4.08 % at 5 % on both passes and the block counts',
    'v14_tc32_p10_2': 'as v14_tc32_p10_1',
    'v14_tc32_p1_2': 'as v14_tc32_p10_1',
    'v14_f2_joint5': "49.3: v17a prints '49' over two runs (v17_f2_ge5)",
    'minirf_base_looks': "the Mini-RF baseline mode's 16 looks: printed in neither v17a nor its supplement",
    'lit_links': 'the 75 raw links of the search flow: printed in neither v17a nor its supplement',
    'g2_hermite': 'moved to the Supplementary Material (S-I Mini-RF / S-II literature search) in v17a; audited against the supplement (SUPPLEMENT_AUDIT)',
    'g2_rozh': 'moved to the Supplementary Material (S-I Mini-RF / S-II literature search) in v17a; audited against the supplement (SUPPLEMENT_AUDIT)',
    'g2_main': 'moved to the Supplementary Material (S-I Mini-RF / S-II literature search) in v17a; audited against the supplement (SUPPLEMENT_AUDIT)',
    'g2_schom': 'moved to the Supplementary Material (S-I Mini-RF / S-II literature search) in v17a; audited against the supplement (SUPPLEMENT_AUDIT)',
    'g2_card': 'moved to the Supplementary Material (S-I Mini-RF / S-II literature search) in v17a; audited against the supplement (SUPPLEMENT_AUDIT)',
    'g2_byrg': 'moved to the Supplementary Material (S-I Mini-RF / S-II literature search) in v17a; audited against the supplement (SUPPLEMENT_AUDIT)',
    'g2_doll': 'moved to the Supplementary Material (S-I Mini-RF / S-II literature search) in v17a; audited against the supplement (SUPPLEMENT_AUDIT)',
    'g2_stev': 'moved to the Supplementary Material (S-I Mini-RF / S-II literature search) in v17a; audited against the supplement (SUPPLEMENT_AUDIT)',
    'n_hermite_sd': 'moved to the Supplementary Material (S-I Mini-RF / S-II literature search) in v17a; audited against the supplement (SUPPLEMENT_AUDIT)',
    'n_hermite_g1': 'moved to the Supplementary Material (S-I Mini-RF / S-II literature search) in v17a; audited against the supplement (SUPPLEMENT_AUDIT)',
    'n_hermite_g2': 'moved to the Supplementary Material (S-I Mini-RF / S-II literature search) in v17a; audited against the supplement (SUPPLEMENT_AUDIT)',
    'n_card_g1': 'moved to the Supplementary Material (S-I Mini-RF / S-II literature search) in v17a; audited against the supplement (SUPPLEMENT_AUDIT)',
    'n_card_g2': 'moved to the Supplementary Material (S-I Mini-RF / S-II literature search) in v17a; audited against the supplement (SUPPLEMENT_AUDIT)',
    'pm_spread': 'moved to the Supplementary Material (S-I Mini-RF / S-II literature search) in v17a; audited against the supplement (SUPPLEMENT_AUDIT)',
    'lit_unique': 'moved to the Supplementary Material (S-I Mini-RF / S-II literature search) in v17a; audited against the supplement (SUPPLEMENT_AUDIT)',
    'minirf_zoom_cdr': 'moved to the Supplementary Material (S-I Mini-RF / S-II literature search) in v17a; audited against the supplement (SUPPLEMENT_AUDIT)',
    'lit_excluded': 'moved to the Supplementary Material (S-I Mini-RF / S-II literature search) in v17a; audited against the supplement (SUPPLEMENT_AUDIT)',
    'lit_fulltext': 'moved to the Supplementary Material (S-I Mini-RF / S-II literature search) in v17a; audited against the supplement (SUPPLEMENT_AUDIT)',
    'lit_abstract': 'moved to the Supplementary Material (S-I Mini-RF / S-II literature search) in v17a; audited against the supplement (SUPPLEMENT_AUDIT)',
}

#: Quantified rows retired, moved or re-anchored by v17a.
RETIRED_QUANTIFIED_V17A = {
    'q_v11_iii_bias': '(iii) reworded: v17a says one record examined reports it [spudis2013]',
    'q_proxy_every_case': "re-anchored: v17a says 'all give a proxy median of 0.00043' (q_v17_proxy_all)",
    'q_v14_cpr_none_second': "reworded: v17a says 'never the same one' (q_v17_never_same); pass 2's 0 CPR rejections not printed",
    'q_lit_one_of_25': 'moved to S-II (SUPPLEMENT_QUANTIFIED)',
    'q_lit_none_crit': 'moved to S-II (SUPPLEMENT_QUANTIFIED)',
    'q_cardanus_uniformly': 'moved to S-I (SUPPLEMENT_QUANTIFIED)',
}
