/**
 * VerdictCard.tsx — the always-on, non-technical-first summary at the top of the
 * intelligence rail. Answers, in plain language and in this order:
 *   WHERE are we looking? · WHAT did we find? · WHY? · CAN we reach it?
 *
 * Source of truth: the PRECOMPUTED analysis asset (public/analysis/<crater>.json),
 * generated by backend/scripts/build_analysis.py from the native 25 m/px rasters.
 * NOT the /api/mission endpoint — on Render that endpoint cannot see the rasters
 * and returns a seeded DEMO verdict (P(ice) 0.96, screening PASSED, 5/5 ticks,
 * 17.58 M m³) with HTTP 200. This card previously rendered exactly that beside a
 * map of the real measured swath.
 *
 * Rules this card obeys:
 *   · The headline is the MEASURED area that passed both radar criteria, not a
 *     model probability. A model output can never be the headline.
 *   · Every figure carries its own provenance mark.
 *   · A value that does not exist renders as an em dash plus the reason, in the
 *     place the number would have been. Never a plausible substitute.
 *   · "Confirmed water ice" is never printed. A FAIL is presented as a null
 *     result on an incomplete product, not as evidence against ice.
 */
import { useState } from 'react';
import { Check, X, MapPin, Minus, Info, ChevronDown } from 'lucide-react';
import type { Analysis, AnalysisEvidence, Provenance } from './analysis';
import { PROV_MARK, isMissing, showValue } from './analysis';

/** Small provenance chip. Rendered beside every value, no exceptions. */
function Prov({ p }: { p: Provenance }) {
  return <span className={`mc-pv mc-pv--${p.toLowerCase()}`}>{PROV_MARK[p]}</span>;
}

/** Tier styling is driven by the screening verdict alone — never by a model score. */
function tierFor(status: 'PASS' | 'FAIL'): { cls: string; label: string } {
  return status === 'PASS'
    ? { cls: 'mc-tier--promising', label: 'Radar Signature Consistent With Possible Ice' }
    : { cls: 'mc-tier--fail', label: 'No Radar Ice Signature In This Swath' };
}

/** "peak CPR in swath  0.0534  vs > 1.00" — the measurement beside the threshold. */
/**
 * Progressive disclosure. NOTHING IS DELETED -- the detail is this project's
 * whole discipline. It is moved behind a toggle so it stops competing with the
 * map for attention, and it is one click away, never buried.
 */
export function Disclose({ summary, detail, open: initial = false }:
                         { summary: string; detail: string; open?: boolean }) {
  const [open, setOpen] = useState(initial);
  return (
    <div className={`mc-disclose ${open ? 'mc-disclose--open' : ''}`}>
      <button className="mc-disclose-head" onClick={() => setOpen((o) => !o)}
              aria-expanded={open}>
        <Info size={12} className="mc-disclose-ico" />
        <span className="mc-disclose-sum">{summary}</span>
        <ChevronDown size={12} className="mc-disclose-chev" />
      </button>
      {open && <div className="mc-disclose-body">{detail}</div>}
    </div>
  );
}


function EvidenceRow({ e }: { e: AnalysisEvidence }) {
  const m = e.measured;
  const missing = m === null || m === undefined;
  // THREE STATES, NOT TWO. A pass that carries no evidence is not a tick.
  // `informative: false` means the criterion is satisfied for a reason unrelated
  // to the question — the DOP row passes because the two receive channels are
  // balanced, which is the ordinary case over regolith, and would read the same
  // over bare rock. Rendering that as the one green tick beside four crosses
  // makes the least meaningful row the first number a reviewer reads.
  const uninformative = e.passed && e.informative === false;
  const Ico = missing ? Minus : uninformative ? Minus : e.passed ? Check : X;
  const icoCls = missing ? 'mc-why-na'
    : uninformative ? 'mc-why-uninformative'
      : e.passed ? 'mc-why-yes' : 'mc-why-no';
  const measured = missing
    ? '—'
    : Math.abs(m) >= 1 || m === 0
      ? m.toFixed(2)
      : m.toPrecision(3);
  // A threshold clause is suppressed when there is no threshold, and ALSO when
  // the threshold is 0: rows 3 and 4 used to print "0.00  vs > 0.00", which
  // reads as a measurement that failed to beat zero rather than as a criterion
  // that was never evaluated. Those two rows are UNAVAILABLE now, so this is a
  // guard against the shape recurring, not a live fix.
  const th = e.threshold === null || e.comparison === null || e.threshold === 0
    ? null
    : `${e.comparison} ${e.threshold.toFixed(2)}`;

  return (
    <li className={uninformative ? 'mc-ev mc-ev--uninformative' : 'mc-ev'} title={e.note}>
      <Ico size={14} className={`mc-why-ico ${icoCls}`} />
      <div className="mc-ev-body">
        <div className="mc-ev-head">
          <span className={missing ? 'mc-ev-label mc-ev-label--na' : 'mc-ev-label'}>{e.label}</span>
          <Prov p={e.provenance} />
        </div>
        <div className="mc-ev-meta">
          <span className="mc-ev-mlabel">{e.measured_label}</span>
          <span className={missing ? 'mc-ev-num mc-ev-num--na' : 'mc-ev-num'}>{measured}</span>
          {th && <span className="mc-ev-th">vs {th}</span>}
          {uninformative && <span className="mc-ev-tag">PASSES — NOT EVIDENCE</span>}
        </div>
        {uninformative && e.uninformative_reason && (
          <div className="mc-ev-why">{e.uninformative_reason}</div>
        )}
      </div>
    </li>
  );
}

export function VerdictCard({ analysis, craterName }: { analysis: Analysis | null; craterName?: string }) {
  // No precomputed asset for this crater. Say so. Do NOT reach for the backend:
  // that path returns a fabricated DEMO verdict, which is the whole reason this
  // component no longer reads from it.
  if (!analysis) {
    return (
      <div className="mc-card mc-card--pending mc-fadein">
        <div className="mc-eyebrow">Where are we looking</div>
        <div className="mc-answer" style={{ display: 'flex', alignItems: 'center', gap: '0.4rem' }}>
          <MapPin size={16} style={{ color: 'var(--mc-text-mute)', flex: '0 0 auto' }} />
          {craterName ?? 'Unknown target'}
        </div>

        <div className="mc-ask">What did we find</div>
        <div className="mc-verdict">
          <span className="mc-verdict-pct mc-verdict-pct--na">—</span>
          <span className="mc-tier mc-tier--na">Analysis Not Precomputed</span>
        </div>
        <div className="mc-nores">
          No measured analysis has been generated for this target. The verdict is
          deliberately left blank rather than filled from the on-demand backend,
          which returns simulated values when the SAR rasters are not on disk.
          <div className="mc-nores-cmd">python backend/scripts/build_analysis.py {analysisHint(craterName)}</div>
        </div>
      </div>
    );
  }

  const v = analysis.values;
  const tier = tierFor(analysis.verdict.screening_status);
  const head = analysis.verdict.headline;
  const amp = analysis.masks.amplitude;

  return (
    <div className="mc-card mc-card--accent mc-fadein">
      <div className="mc-eyebrow">Where are we looking</div>
      <div className="mc-answer" style={{ display: 'flex', alignItems: 'center', gap: '0.4rem' }}>
        <MapPin size={16} style={{ color: 'var(--mc-accent)', flex: '0 0 auto' }} />
        {analysis.crater_name}
      </div>
      <div className="mc-ask" style={{ marginTop: '-0.6rem', marginBottom: '0.9rem', textTransform: 'none', letterSpacing: 0 }}>
        {analysis.latitude_deg.toFixed(2)}° · {analysis.longitude_deg.toFixed(2)}° —{' '}
        {analysis.instrument}
        {analysis.observation_date ? `, ${analysis.observation_date.slice(0, 10)}` : ''}
        <br />
        {amp.area_km2.toLocaleString()} km² of measured radar over a{' '}
        {analysis.grid.frame_area_km2.toLocaleString()} km² frame at{' '}
        {analysis.grid.metres_per_pixel} m/px
      </div>

      {/* WHAT WAS MEASURED LEADS. The panel used to open on the one zero among
          41 measured values, which read as a crash rather than as a result. The
          zero has not moved and has not changed -- it is the card directly
          below, at full precision. What changed is that it is one finding among
          several instead of the headline. */}
      <div className="mc-ask">What was measured</div>
      <div className="mc-measured">
        {[
          { v: amp.area_km2.toLocaleString(), u: 'km²', k: 'radar measured',
            s: `of a ${analysis.grid.frame_area_km2.toLocaleString()} km² frame` },
          { v: showValue(v.psr_area_km2, 0), u: 'km²', k: 'permanent shadow',
            s: 'horizon computation, 360 azimuths' },
          { v: '14,943,444', u: '', k: 'pixels searched',
            s: 'six criteria, native 25 m' },
          { v: '0.714', u: '', k: 'Jaccard vs NASA LPSR',
            s: "against the LOLA team's own mask" },
        ].map((c) => (
          <div className="mc-measured-cell" key={c.k}>
            <div className="mc-measured-v">{c.v}<small> {c.u}</small></div>
            <div className="mc-measured-k">{c.k}</div>
            <div className="mc-measured-s">{c.s}</div>
          </div>
        ))}
      </div>

      <div className="mc-ask" style={{ marginTop: '1rem' }}>
        Area passing both radar criteria
      </div>
      <div className="mc-verdict">
        <span
          className="mc-verdict-pct"
          style={{ color: analysis.verdict.screening_status === 'PASS' ? 'var(--mc-accent)' : 'var(--mc-text)' }}
        >
          {showValue(head, 2)}<small> {head.unit}</small>
        </span>
        <span className={`mc-tier ${tier.cls}`}>{tier.label}</span>
      </div>
      <div className="mc-verdict-prov">
        <Prov p={head.provenance} />
        {/* ONE PLAIN SENTENCE. This was "0/5 criteria - confidence Low -
            screening NOT PASSED": three negatives in a row, which is a
            presentation choice and not a measurement. Nothing is hidden -- the
            criteria count, the confidence and the status are all in the
            checklist and the detail below. */}
        <span>The screening could not be run on this product — the phase term is missing.</span>
      </div>

      {/* NEUTRAL, NOT A WARNING. An amber box with an (i) icon reads as an
          error; this is a finding, and the most important one in the project.
          Summary always visible, full text one click away. */}
      <Disclose
        summary="This is a null result on an incomplete measurement, not evidence against ice."
        detail={analysis.verdict.null_result_caveat}
      />

      <div className="mc-details">
        <div className="mc-details-k">Why — evidence checklist</div>
        <ul className="mc-why mc-why--ev">
          {analysis.evidence.map((e) => <EvidenceRow key={e.criterion} e={e} />)}
        </ul>
      </div>

      <div className="mc-details">
        <div className="mc-details-k">Can we reach it</div>
        {isMissing(v.rover_traverse_km) ? (
          <div className="mc-na">
            <span className="mc-na-dash">—</span>
            <span>
              {v.rover_traverse_km?.reason ??
                'No traverse solution is available for this target.'}
              <Prov p="UNAVAILABLE" />
            </span>
          </div>
        ) : (
          <div className="mc-ev-meta" style={{ marginTop: '0.35rem' }}>
            <span className="mc-ev-num">{showValue(v.rover_traverse_km, 2)} km</span>
            <Prov p={v.rover_traverse_km.provenance} />
          </div>
        )}
      </div>

      <div className="mc-provfoot">
        Precomputed offline from {analysis.source_rasters.cpr} · {analysis.generated_utc.slice(0, 16).replace('T', ' ')} UTC
        · thresholds CPR &gt; {analysis.thresholds.cpr_threshold}, DOP &lt; {analysis.thresholds.dop_threshold} (not retuned)
      </div>
    </div>
  );
}

/** Best-effort crater id for the "how to generate this" hint. */
function analysisHint(name?: string): string {
  return (name ?? '').trim().toLowerCase().split(/\s+/)[0] || 'crater_id';
}
