"""
assert_figures_embed_fonts.py -- G26. The figures carry no Type 3 font.

    python paper/assert_figures_embed_fonts.py [--inject WHICH]

WHY
---
IEEE PDF eXpress rejects Type 3 fonts, and a figure is the easiest place for one
to arrive unnoticed: matplotlib's default PDF backend emits Type 3 unless
`pdf.fonttype` is set to 42. `make_figures.py` sets it and uses STIX, which ships
inside matplotlib, so the output is identical on every machine -- but "the script
sets it" is a claim about the script, not about the PDFs on disk.

THIS REGENERATES THE FIGURES AND INSPECTS THE BYTES. A figure that was built
before the setting was added, or by a different script, would still be sitting in
the directory passing on reputation.

pdffonts (poppler-utils) is the reference tool and is not installed everywhere.
When it is absent this gate reads the PDF's own font dictionaries directly --
`/Subtype /Type3` and the presence of a `/FontFile*` descriptor -- rather than
reporting a check that did not run as a pass. A submission gate that passes
because it could not look is the one failure mode a submission gate must not
have.
"""
from __future__ import annotations

import argparse
import re
import shutil
import subprocess
import sys
import zlib
from pathlib import Path

HERE = Path(__file__).resolve().parent
FIGURES = ["fig1_degeneracy.pdf", "fig2_enl.pdf",
           "fig3_detection.pdf", "fig4_external.pdf"]

for _s in (sys.stdout, sys.stderr):
    try:
        _s.reconfigure(encoding="utf-8", errors="replace")
    except (AttributeError, OSError):
        pass

INJECTIONS = ("type3", "unembedded", "missing")


def inspect_bytes(pdf: Path) -> dict:
    """Font subtypes and embedded-file descriptors, read from the PDF itself.

    Object streams are decompressed where they are Flate-encoded, because a
    modern writer puts the font dictionaries inside one and a raw scan would
    find nothing and call that clean.
    """
    raw = pdf.read_bytes()
    chunks = [raw]
    for m in re.finditer(rb"stream\r?\n", raw):
        start = m.end()
        end = raw.find(b"endstream", start)
        if end == -1:
            continue
        try:
            chunks.append(zlib.decompress(raw[start:end]))
        except zlib.error:
            pass
    blob = b"".join(chunks)
    return {
        "type3": len(re.findall(rb"/Subtype\s*/Type3", blob)),
        "fonts": len(re.findall(rb"/Type\s*/Font", blob)),
        "fontfiles": len(re.findall(rb"/FontFile[23]?\b", blob)),
    }


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--inject", choices=INJECTIONS)
    ap.add_argument("--skip-build", action="store_true")
    args = ap.parse_args()

    print("=" * 78)
    print("G26 — the figures embed their fonts and carry no Type 3")
    print("=" * 78)

    script = HERE / "make_figures.py"
    if not script.is_file():
        print(f"  GATE FAIL — {script} is absent.")
        return 1

    if not args.skip_build:
        r = subprocess.run([sys.executable, str(script)], cwd=str(HERE),
                           capture_output=True, text=True)
        if r.returncode != 0:
            print("  GATE FAIL — make_figures.py did not run:")
            print("   ", (r.stderr or r.stdout).strip().splitlines()[-1:])
            return 1
        print(f"  regenerated by {script.name}")

    have_pdffonts = shutil.which("pdffonts") is not None
    print(f"  pdffonts available: {have_pdffonts}"
          + ("" if have_pdffonts else "  -> reading the PDF font dictionaries directly"))
    print()

    bad: list[str] = []
    print(f"  {'figure':<24}{'fonts':>7}{'Type 3':>9}{'embedded':>10}")
    for name in FIGURES:
        pdf = HERE / name
        if args.inject == "missing" and name == FIGURES[0]:
            print(f"  --inject missing: {name} treated as absent")
            bad.append(f"{name} was not produced")
            continue
        if not pdf.is_file():
            bad.append(f"{name} is absent; make_figures.py did not produce it")
            print(f"  {name:<24}{'-':>7}{'-':>9}{'ABSENT':>10}")
            continue

        info = inspect_bytes(pdf)
        t3, nf, ff = info["type3"], info["fonts"], info["fontfiles"]
        if args.inject == "type3" and name == FIGURES[0]:
            print(f"  --inject type3: {name} reported with a Type 3 font")
            t3 = 1
        if args.inject == "unembedded" and name == FIGURES[0]:
            print(f"  --inject unembedded: {name} reported with no font files")
            ff = 0

        if have_pdffonts:
            out = subprocess.run(["pdffonts", str(pdf)],
                                 capture_output=True, text=True).stdout
            rows = out.splitlines()[2:]
            t3 = len([l for l in rows if "Type 3" in l])
            unemb = [l for l in rows if l.split() and l.split()[-4] == "no"]
            ff = len(rows) - len(unemb)
            nf = len(rows)

        print(f"  {name:<24}{nf:>7}{t3:>9}{ff:>10}")
        if t3:
            bad.append(f"{name} carries {t3} Type 3 font(s); IEEE PDF eXpress "
                       f"rejects them. make_figures.py must set pdf.fonttype=42.")
        if nf and not ff:
            bad.append(f"{name} declares {nf} font(s) and embeds none")

    print()
    if args.inject:
        if bad:
            print(f"  INJECTION CAUGHT ({args.inject}). The gate works.")
            for b in bad:
                print(f"    {b}")
            return 0
        print(f"  INJECTION NOT CAUGHT ({args.inject}).")
        return 1

    if bad:
        print("  GATE FAIL")
        for b in bad:
            print(f"    - {b}")
        return 1
    print("  GATE PASS — every figure regenerates, declares its fonts, embeds")
    print("  them, and carries no Type 3.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
